### PR TITLE
Aligned baseline policies criticality between code and document

### LINKED ISSUE #949: some baseline policies in ScubaGear report have incorrect criticality values
# 💡 Summary #

Some of the criticality values displayed in the Sharepoint report were found to be inconsistent with the secure baseline document. The scope of this issue is to correct these in Sharepoint and examine / correct other baselines.

## Screenshot examples ##

image

image

## Implementation notes ##

- [ ] Review each of the policies in the Sharepoint Rego and compare their criticality values with the baseline document. Modify the Rego criticalities to align with the baselines wherever discrepancies are found.
- [ ] Repeat this process for all other baselines (AAD, Defender, etc.)

### PR DESCRIPTION
**Pull request by crutchfield**
## 🗣 Description ##

SharePoint and Teams had mis-alignment between code and secure baseline document for policy criticality.  Modified code to align with document.

closes #949 

## 💭 Motivation and context ##

This is require to generate the correct criticality in the report. 

## 🧪 Testing ##

Executed SharePoint and Teams to verify modified alignments display properly. 
Manually review all baseline documents against code to check for other criticality issues.

SharePoint: 1.1, 1.2, 3.1, 3.2, 3.3
Teams: 6.2

## 📷 Screenshots (if appropriate) ##
image

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] Changes are sized such that they do not touch excessive number of files.
- [X] *All* future TODOs are captured in issues, which are referenced in code comments.
- [X] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [X] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [X] All relevant type-of-change labels added.
- [X] All relevant project fields are set.
- [X] All relevant repo and/or project documentation updated to reflect these changes.
- [X] Unit tests added/updated to cover PowerShell and Rego changes.
- [X] Functional tests added/updated to cover PowerShell and Rego changes.
- [X] All relevant functional tests passed.
- [X] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by tkol2022 — APPROVED** [review]
I ran the tool and it reported with the corrected criticalities. I also double checked that they align with the baseline documents.

**Review by nanda-katikaneni — APPROVED** [review]
Ran ScubaGear in the fixed branch to verify that SPO report shows correct criticality.

**Comment by crutchfield** [comment]
@nanda-katikaneni PR is ready to merge - smoke test issue not related.

**Comment by crutchfield** [comment]
@nanda-katikaneni PR is ready to merge - smoke test issue not related.

**Pull request merged**
