### PR TITLE
Modify Sharepoint policies to only execute when applicable

### LINKED ISSUE #892: Non-Applicable policies should not generate warnings.
# 🐛 Summary #

What's wrong? Please be specific.

MS.SHAREPOINT.3.2v1

Generates a warning when both file types are set to 2 and input.OneDrive_PnP_Flag == false

## To reproduce ##

1. Set     
        TenantPolicy.FileAnonymousLinkType = 2
        FolderAnonymousLinkType = 2
        OneDrive_PnP_Flag == false

1. Then this
Run SCUBA

## Expected behavior ##
No warning as policy is not applicable

What did you expect to happen that didn't?
A warning was generated.

## Any helpful log output or screenshots ##

Requirement not met: both files and folders are not limited to view for Anyone

### PR DESCRIPTION
**Pull request by mitchelbaker-cisa**
#  #
  

## 🗣 Description ##

Several of the Sharepoint policies execute even in cases when they are not applicable. The policies for Sharepoint 1.3, 3,1, 3.2, and 3.3 have been updated to produce N/A messages when warranted. If the configuration settings apply, then the policy executes normally. 

**Policy 1.3**
- Executes normally when the external sharing slider is set to any value other than Only people in your organization.
- Produces N/A message when set to Only People in your organization. 
- Unit tests updated.
- Functional tests updated.

**Policy 1.4**
- Executes normally when the external sharing slider is set to any value other than Only people in your organization.
- Produces N/A message when set to Only People in your organization. 
- Unit tests updated.
- Functional tests updated.

**Policy 3.1**
- Executes normally when the external sharing slider is set to Anyone. 
- Produces N/A message when set to Only people in your organization, Existing guests, or New and existing guests.
- Unit tests updated.
- Functional tests updated.

**Policy 3.2**
- Executes normally when the external sharing slider is set to Anyone. 
- Checks that both file and folder link types equal 1 (View)
- Produces N/A message when set to Only people in your organization, Existing guests, or New and existing guests.
- Unit tests updated.
- Functional tests not complete, they currently fail because `input.OneDrive_PnP_Flag` == false is checked in the configuration code which can't be pulled from Set-SPOTenant cmdlet.

**Policy 3.3**
- Executes normally when the external sharing slider is set to Anyone or New and existing guests.
- Produces N/A message when set to Only people in your organization or Existing guests.
- Unit tests updated.
- Functional tests updated.

## 💭 Motivation and context ##

Epic: https://github.com/cisagov/ScubaGear/issues/1064

closes https://github.com/cisagov/ScubaGear/issues/1062
closes https://github.com/cisagov/ScubaGear/issues/952
closes https://github.com/cisagov/ScubaGear/issues/951
closes https://github.com/cisagov/ScubaGear/issues/950
closes #892 

Output in the reports was not accurately depicting tenant configuration settings. 

## 🧪 Testing ##

Check that unit tests pass: 
```
.\RunUnitTests.ps1 -p sharepoint
```

Check that functional tests pass for each policy ID:
- MS.SHAREPOINT.1.3v1
- MS.SHAREPOINT.3.1v1
- MS.SHAREPOINT.3.2v1
- MS.SHAREPOINT.3.3v1

```
$TestContainers = @() 
$TestContainers += New-PesterContainer -Path "Testing/Functional/Products" `
-Data @{ 
    Thumbprint = "<your-thumbprint>"; 
    TenantDomain = "<tenant-domain>"; 
    TenantDisplayName = "<display-name>"; 
    AppId = "<app-id>"; 
    ProductName = "sharepoint"; 
    M365Environment = "gcc";
    Variant = "<spo/pnp>"
} 
$PesterConfig = @{
        Run = @{Container = $TestContainers}
        Filter = @{Tag = @("<Policy ID>")}
        Output = @{Verbosity = 'Detailed'}
    }

$Config = New-PesterConfiguration -Hashtable $PesterConfig 
Invoke-Pester -Configuration $Config
```

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by tkol2022** [comment]
### Unit test review 1.3
The unit tests for policy 1.3 are missing the following two _Incorrect test scenarios - both of these should produce a false.

```
{
                "SharingCapability": 2,
                "SharingDomainRestrictionMode": 0
            }

{
                "SharingCapability": 3,
                "SharingDomainRestrictionMode": 0
            }
```

**Comment by tkol2022** [comment]
### Inconsistencies in functional test plan
The following issues were found with the functional test plans sharepoint.spo.testplan.yaml and sharepoint.pnp.testplan.yaml.

- Some of the test scenarios are named incorrectly. Notice in the screenshot below that the test case "MS.SHAREPOINT.2.2v1 Non-compliant - DefaultSharingLinkType = Edit" should be named "MS.SHAREPOINT.2.2v1 Non-compliant - **DefaultLinkPermission** = Edit"

image

- Some of the test scenarios change field values that are unrelated to the specific policy being tested. For example the policy 3.1 test scenarios reference the field "DefaultSharingLinkType" but the 3.1 policy check has nothing to do with that field. Fields that are unrelated to the policy should be removed from the tests as they are unnecessary and make maintenance more challenging.
image

**Comment by tkol2022** [comment]
### Improving the functional & unit tests for N/A cases
When testing N/A scenarios, I recommend setting the policy field to both compliant and non compliant values so that we can ensure the N/A works as expected. Let's take policy 3.1 as an example. Write N/A test scenarios that exercise the following conditions. Since Only people in your organization is configured, both scenarios produce N/A.

- set the RequireAnonymousLinksExpireInDays < 30 & external sharing slider to Only people in your organization
- set the RequireAnonymousLinksExpireInDays > 30 & external sharing slider to Only people in your organization

**Comment by ahuynhMITRE** [comment]
currently getting this error message when running through the scenarios described in this pr: 
image

**Review by ahuynhMITRE — APPROVED** [review]
was able to resolve my errors after meeting with @nanda-katikaneni  yesterday. went through each of the scenarios documented in the PR with no issues. @nanda-katikaneni also mentioned he already forwarded long issues associated with the functional tests so no further comments from me!

**Review by nanda-katikaneni — APPROVED** [review]
Ran SharePoint tests - verified the changed behavior of executing policies only when applicable. There is a separate but related functional testing issue #1093 - (that issue is for both main branch and this branch and seems not related to this change). 
Approving this PR.

**Pull request merged**
