### PR TITLE
Add MSGraph and SPO library max versions

### LINKED ISSUE #889: Get-SPOTenant throws error, preventing Sharepoint from being scanned.
# 🐛 Summary #

What's wrong? Please be specific.

Get-SPOTenant throws error, preventing Sharepoint from being scanned.

WARNING: Error running Get-SPOTenant. Unable to cast object of type 'System.String' to type
'Microsoft.Online.SharePoint.TenantAdministration.EsignatureThirdPartyProvidersInfo'.

1. Invoke-SCuBA, which at some point will run a Get-SPOTenant command

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

WARNING: Error running Get-SPOTenant. Unable to cast object of type 'System.String' to type
'Microsoft.Online.SharePoint.TenantAdministration.EsignatureThirdPartyProvidersInfo'.

```console

```

Add any screenshots of the problem here.

### LINKED ISSUE #903: AAD module generates an error at launch
# 🐛 Summary #

The AAD module generates an error at launch. All prerequisites are correct.

## To reproduce ##

Invoke-SCuBA -ProductNames aad -Verbose

## Any helpful log output or screenshots ##
PS C:\temp\ScubaGear-1.1.0> Invoke-SCuBA -ProductNames aad -Verbose
COMMENTAIRES : Suppression de la fonction importée « Select-DohServer ».
COMMENTAIRES : Suppression de la fonction importée « Get-ScubaDmarcRecord ».
COMMENTAIRES : Suppression de la fonction importée « Invoke-RobustDnsTxt ».
COMMENTAIRES : Suppression de la fonction importée « Get-ScubaSpfRecord ».
COMMENTAIRES : Suppression de la fonction importée « Get-ScubaDkimRecord ».
COMMENTAIRES : Suppression de la fonction importée « Get-EXOTenantDetail ».
COMMENTAIRES : Suppression de la fonction importée « Export-EXOProvider ».
COMMENTAIRES : Suppression de la fonction importée « Get-PrivilegedUser ».
COMMENTAIRES : Suppression de la fonction importée « Get-PrivilegedRole ».
COMMENTAIRES : Suppression de la fonction importée « Get-AADTenantDetail ».
COMMENTAIRES : Suppression de la fonction importée « Export-AADProvider ».
COMMENTAIRES : Suppression de la fonction importée « Export-DefenderProvider ».
COMMENTAIRES : Suppression de la fonction importée « Get-TeamsTenantDetail ».
COMMENTAIRES : Suppression de la fonction importée « Export-TeamsProvider ».
COMMENTAIRES : Suppression de la fonction importée « Export-SharePointProvider ».
COMMENTAIRES : Suppression de la fonction importée « Invoke-Rego ».
COMMENTAIRES : Suppression de la fonction importée « New-Report ».
COMMENTAIRES : Suppression de la fonction importée « Import-SecureBaseline ».
COMMENTAIRES : Suppression de la fonction importée « Disconnect-SCuBATenant ».
COMMENTAIRES : Suppression de la fonction importée « Connect-Tenant ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportAADProvider.psm1 ».
COMMENTAIRES : Exportation de la fonction « Export-AADProvider ».
COMMENTAIRES : Exportation de la fonction « Get-AADTenantDetail ».
COMMENTAIRES : Exportation de la fonction « Get-PrivilegedUser ».
COMMENTAIRES : Exportation de la fonction « Get-PrivilegedRole ».
COMMENTAIRES : Importation de la fonction « Export-AADProvider ».
COMMENTAIRES : Importation de la fonction « Get-AADTenantDetail ».
COMMENTAIRES : Importation de la fonction « Get-PrivilegedRole ».
COMMENTAIRES : Importation de la fonction « Get-PrivilegedUser ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportDefenderProvider.psm1 ».
COMMENTAIRES : Exportation de la fonction « Export-DefenderProvider ».
COMMENTAIRES : Importation de la fonction « Export-DefenderProvider ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportEXOProvider.psm1 ».
COMMENTAIRES : Exportation de la fonction « Export-EXOProvider ».
COMMENTAIRES : Exportation de la fonction « Get-EXOTenantDetail ».
COMMENTAIRES : Exportation de la fonction « Select-DohServer ».
COMMENTAIRES : Exportation de la fonction « Invoke-RobustDnsTxt ».
COMMENTAIRES : Exportation de la fonction « Get-ScubaSpfRecord ».
COMMENTAIRES : Exportation de la fonction « Get-ScubaDkimRecord ».
COMMENTAIRES : Exportation de la fonction « Get-ScubaDmarcRecord ».
COMMENTAIRES : Importation de la fonction « Export-EXOProvider ».
COMMENTAIRES : Importation de la fonction « Get-EXOTenantDetail ».
COMMENTAIRES : Importation de la fonction « Get-ScubaDkimRecord ».
COMMENTAIRES : Importation de la fonction « Get-ScubaDmarcRecord ».
COMMENTAIRES : Importation de la fonction « Get-ScubaSpfRecord ».
COMMENTAIRES : Importation de la fonction « Invoke-RobustDnsTxt ».
COMMENTAIRES : Importation de la fonction « Select-DohServer ».                                                         COMMENTAIRES : Importation de la fonction « Export-PowerPlatformProvider ».                                             COMMENTAIRES : Importation de la fonction « Get-PowerPlatformTenantDetail ».                                            COMMENTAIRES : Chargement du module à partir du chemin                                                                  « C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportSharePointProvider.psm1 ».                       COMMENTAIRES : Exportation de la fonction « Export-SharePointProvider ».
COMMENTAIRES : Importation de la fonction « Export-SharePointProvider ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Providers\ExportTeamsProvider.psm1 ».
COMMENTAIRES : Exportation de la fonction « Export-TeamsProvider ».
COMMENTAIRES : Exportation de la fonction « Get-TeamsTenantDetail ».
COMMENTAIRES : Importation de la fonction « Export-TeamsProvider ».
COMMENTAIRES : Importation de la fonction « Get-TeamsTenantDetail ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\Connection\Connection.psm1 ».
COMMENTAIRES : Importation de la fonction « Connect-Tenant ».
COMMENTAIRES : Importation de la fonction « Disconnect-SCuBATenant ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\RunRego\RunRego.psm1 ».
COMMENTAIRES : Importation de la fonction « Invoke-Rego ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\CreateReport\CreateReport.psm1 ».
COMMENTAIRES : Importation de la fonction « Import-SecureBaseline ».
COMMENTAIRES : Importation de la fonction « New-Report ».
COMMENTAIRES : Chargement du module à partir du chemin
« C:\temp\ScubaGear-1.1.0\PowerShell\ScubaGear\Modules\ScubaConfig\ScubaConfig.psm1 ».
COMMENTAIRES : Importation de la fonction « Copy-ScubaBaselineDocument ».
Fatal Error involving the Report Creation.
            Ending ScubaGear execution. See the exception message for more details: Objet non valide passé, ':' ou '}'
attendu. (677065):         {
                "baseline_version": "1",
                "module_version": "1.1.0",
                "date": "02/10/2024 05:38:58 Paris, Madrid",
                "tenant_details": [
    {
        "AADAdditionalData":  {
                                  "AssignedPlans":  [
                                                        {
                                                            "AssignedDateTime":  "Date(1707461129000)",
                                                            "CapabilityStatus":  "Suspended",
                                                            "Service":  "MicrosoftCommunicationsOnline",

Add any screenshots of the problem here.

### LINKED ISSUE #904: Unable to generate report
Hello, 
I executed setup.ps1 and all modules was installed.
When starting Invoke-Scuba, after signing and execution code, the console show many errors (i think it's when to generate the HTML report)

   "ExceptIfSubjectOrBodyContainsWords":  [
                                               ],
        "DocumentMatchesPatterns":  [
                                    ],
        "ExceptIfDocumentMatchesPatterns":  [
                                            ],
        "DocumentContainsWords":  [
                                  ],
        "ExceptIfDocumentContainsWords":  [
                                          ],
        "SenderADAttributeMatchesPatterns":  null,
        "ExceptIfSenderADAttributeMatchesPatterns":  null,
        "SenderADAttributeContainsWords":  null,
        "ExceptIfSenderADAttributeContainsWords":  null,
        "RecipientADAttributeMatchesPatterns":  null,
        "ExceptIfRecipientADAttributeMatchesPatterns":  null,
        "RecipientADAttributeContainsWords":  null,
        "ExceptIfRecipientADAttributeContainsWords":  null,
        "ContentCharacterSetContainsWords":  [
                                             ],
        "ExceptIfContentCharacterSetContainsWords":  [
                                                     ],
        "DocumentNameMatchesPatterns":  [
                                        ],
        "ExceptIfDocumentNameMatchesPatterns":  [
                                                ],
        "MessageSizeOver":  "",
        "ExceptIfMessageSizeOver":  "",
        "MessageTypeMatches":  null,
        "ExceptIfMessageTypeMatches":  null,
        "UnscannableDocumentExtensionIs":  [
                                           ],
        "ExceptIfUnscannableDocumentExtensionIs":  [
                                                   ],

  },
    {
        "Description":  null,
        "AllowBroadcastScheduling":  true,
        "AllowBroadcastTranscription":  false,
        "BroadcastAttendeeVisibilityMode":  "EveryoneInCompany",
        "BroadcastRecordingMode":  "AlwaysEnabled",
        "DataSource":  "Memory",
        "Key":  {
                    "ScopeClass":  "Tag",
                    "SchemaId":  "XName=",
                    "AuthorityId":  "Class=Host;InstanceId=00000000-0000-0000-0000-000000000000;XmlRoot=",
                        "DefaultXml":  "SchemaId=;Data=;ConfigObject=;Signature=00000000-0000-0000-0000-000000000000;I
   sModified=True",
                    "XmlRoot":  "name={urn:schema:Microsoft.Rtc.Management.ScopeFramework.2008}AnchoredXmlKey"
                },
        "Identity":  "Tag:Default",
        "ConfigMetadata":  {
                               "Authority":  "Host"
                           }
    }
],
    "teams_successful_commands": [
    "Get-CsTenant",
    "Get-CsTeamsMeetingPolicy",
    "Get-CsTenantFederationConfiguration",
    "Get-CsTeamsClientConfiguration",
    "Get-CsTeamsAppPermissionPolicy",
    "Get-CsTeamsMeetingBroadcastPolicy"
],
    "teams_unsuccessful_commands": [
]
        }

### PR DESCRIPTION
**Pull request by schrolla**
#  #
  

## 🗣 Description ##

The current ScubaGear depends on a number of Microsoft PowerShell modules to interact with M365 services.  Previously, ScubaGear setup installed the latest version of these libraries available in PSGallery.  This update sets the maximum version for the Microsoft.Graph.* modules to v2.12.0 and the Microsoft.Online.SharePoint.PowerShell to v16.0.24322.1200 so that newer versions will not be installed.

## 💭 Motivation and context ##

This change is needed due to errors in the upstream modules that causes ScubaGear to fail.  The solution chosen was to "pin" the module versions used to the last working versions until the upstream modules have been fixed to prevent ScubaGear users from receiving these errors.

Closes #889 
Closes #903 
Closes #904 

## 🧪 Testing ##

Changes were tested by verifying failures after removing all Microsoft modules and re-running `Setup.ps1` from the latest ScubaGear main branch.  Then, after updating the `RequiredVersions.ps1` file to pin the max versions, removing all libraries again and re-running `Setup.ps1`.  Confirmed that the max pinned versions of the modules were installed and ran `Invoke-Scuba -p *` with no errors.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by tkol2022** [comment]
### Test Results
Looks like setup installed the expected "pinned" module versions on a virtual machine. I also tested on my laptop.
image

The only remaining comment that I have on this topic is that on my laptop, just running UninstallModules.ps1 one time was not enough to rectify the Sharepoint error. This is because that script only removes the latest version of the respective module. Since my machine was two versions ahead of the pinned Sharepoint version, I had to manually uninstall one more Sharepoint version after I ran UninstallModules. Once I did that my machine was at the expected state as in the screenshot below - and then Sharepoint ran successfully. I'm wondering how we can communicate this to users and provide them guidance.


image

**Review by tkol2022 — APPROVED** [review]
Approved pending resolution of a comment that I left about the fact that getting the machine to a known working state is tricky even with this "pinned" version fix.

**Comment by tkol2022** [comment]
> @tkol2022 Concur that those users that need to downgrade are still in a tricky state. The fix here is meant to prevent more users from getting into that state in the first place more than address those that already are.
> 
> We could certainly log an issue to update the setup script to better account for pinning by checking that no versions outside of those allowed are installed, perhaps. But that could also cause some issues in some other cases. So I'd rather put that as a TODO outside the bugfix and handle any remaining downgrade users via instructions to remove ALL versions of the affected libraries via `Uninstall-Module` before running `Setup.ps1` again.
> 
> Does that seem like a reasonable way forward?
> 
> > ### Test Results
> > Looks like setup installed the expected "pinned" module versions on a virtual machine. I also tested on my laptop. image
> > The only remaining comment that I have on this topic is that on my laptop, just running UninstallModules.ps1 one time was not enough to rectify the Sharepoint error. This is because that script only removes the latest version of the respective module. Since my machine was two versions ahead of the pinned Sharepoint version, I had to manually uninstall one more Sharepoint version after I ran UninstallModules. Once I did that my machine was at the expected state as in the screenshot below - and then Sharepoint ran successfully. I'm wondering how we can communicate this to users and provide them guidance.
> > image

Yes. Right now, I would monitor the Microsoft Github to see if any fixes are in the works. We might not need to do anything - highly likely that others have complained about the modules being broken and Microsoft is fixing it.

**Comment by radiandrew** [comment]
Just chiming in to report that I upgraded to version 16.0.24614.12000 of Microsoft.Online.SharePoint.PowerShell and the issue seems to be fixed. Cannot comment on the MSGraph dependency, but if that's also case there, it would be a good time to decide whether to keep the version pinned or not.

**Comment by tkol2022** [comment]
> Just chiming in to report that I upgraded to version 16.0.24614.12000 of Microsoft.Online.SharePoint.PowerShell and the issue seems to be fixed. Cannot comment on the MSGraph dependency, but if that's also case there, it would be a good time to decide whether to keep the version pinned or not.

Thx a lot for your feedback.

**Pull request merged**
