### PR TITLE
Updated Azure AD policy (MS.AAD.5.2v1) instructions to match updated UI buttonology

### LINKED ISSUE #1044: Azure AD policy (MS.AAD.5.2v1) instructions need an update.
# 🐛 Summary #

Currently the MS.AAD.5.2v1 policy Instructions are inconsistent with M365 Identity UI (it is also inconsistent with other related policies 5.3v1 and 5.4v1). 

In the current instructions for this policy, step 1 says: 
In Azure Active Directory under Manage, select Enterprise Applications.

Change this to:
In Azure Active Directory under Applications, select Enterprise Applications.

## To reproduce ##

1. Open the Azure AD secure baseline configurations and observe the instruction steps for MS.AAD.5.2v1

## Expected behavior ##

Modified instructions to align with new UI buttonology.

### PR DESCRIPTION
**Pull request by ahuynhMITRE**
## 🗣 Description ##

Currently the MS.AAD.5.2v1 policy Instructions are inconsistent with M365 Identity UI (it is also inconsistent with other related policies 5.3v1 and 5.4v1). Modify instructions to align with new UI buttonology.

## 💭 Motivation and context ##

Change required to align with current UI buttonology and be consistent with the other related policies.

Closes #1044 

## 🧪 Testing ##

N/A, markdown change only.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by nanda-katikaneni — APPROVED** [review]
Approved

**Review by mitchelbaker-cisa — APPROVED** [review]

**Comment by ahuynhMITRE** [comment]
@nanda-katikaneni good to merge now that we are on iceberg

**Comment by nanda-katikaneni** [comment]
> @nanda-katikaneni good to merge now that we are on iceberg

@ahuynhMITRE, can you please check PowerShell link failures (may not be related to the changes made in this pr but the pipeline lint test is failing on the branch).

**Comment by ahuynhMITRE** [comment]
> > @nanda-katikaneni good to merge now that we are on iceberg
> 
> @ahuynhMITRE, can you please check PowerShell link failures (may not be related to the changes made in this pr but the pipeline lint test is failing on the branch).

all checks have now passed!

**Pull request merged**
