### PR TITLE
Update SCB acronym to read as "Secure Configuration Baseline" throughout repo

### LINKED ISSUE #1432: Update SCB acronym to be synonymous with "Secure Configuration Baseline" for consistency
# 💡 Summary #

What is the work, as a high-level summary?
Update language across all documentation to ensure that SCB is synonymous with "Secure Configuration Baseline"

## Motivation and context ##

This would be useful because we reference the SCBs are both "Secure Configuration Baseline" and "Security Configuration Baselines" in multiple artifacts. This will make the documentation consistent with "Secure Configuration Baseline".

## Implementation notes ##

Remove and update all instances that note Security Configuration Baseline with Secure Configuration Baseline.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] All instances of Security Configuration Baseline are replaced with Secure Configuration Baseline.

### PR DESCRIPTION
**Pull request by ahuynhMITRE**
#  #
  

## 🗣 Description ##

We have been referencing SCB as both "Security Configuration Baseline" and "Secure Configuration Baseline". This PR and accompanying issue addresses the inconsistency and updates all references to "Secure Configuration Baseline" to match BOD language. 

## 💭 Motivation and context ##

Change is required to have the acronym of SCB to be consistently referred as "Secure Configuration Baseline" matching the BOD language. Using a the replace functionality this has been done throughout the repo.
 
Closes #1432 

## 🧪 Testing ##

Check throughout the repo that "Security Configuration Baseline" instances have been replaced with "Secure Configuration Baseline".

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [x] Resolved all merge conflicts on branch
- [x] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [x] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by mitchelbaker-cisa — APPROVED** [review]
Looks good, doubled checked files throughout Sample-Reports and /docs directory.

**Review by mitchelbaker-cisa — CHANGES_REQUESTED** [review]
There's one remaining location to update in the [README.md](https://github.com/cisagov/ScubaGear/blob/main/README.md).

Screenshot (352)

Occurrences in /Sample-Reports are related to Defender 5.1 which is updated in this PR. All sample report files will be updated by #1466.
Screenshot (354)

**Review by mitchelbaker-cisa — APPROVED** [review]

**Review by gdasher — APPROVED** [review]
LGTM

**Comment by ahuynhMITRE** [comment]
@nanda-katikaneni good to merge

**Pull request merged**
