### PR TITLE
Allow Users to Specify Installing to AllUsers via new $Scope Variable in Initialize-SCuBA

### LINKED ISSUE #882: Should be possible to use -Scope AllUsers when Install-Module is called.
The Install-Module call should be possible with the AllUsers scope.

### PR DESCRIPTION
**Pull request by buidav**
## 🗣 Description ##

- Add `$Scope` to Initialize-SCuBA to let users install to `AllUsers`, a place where all users can access the dependent PowerShell modules, rather than just the `CurrentUser` on their system. 

## 💭 Motivation and context ##

Closes #882 

## 🧪 Testing ##

- Run `Initalize-SCuBA` by itself. Should be the normal behavior.
- Then run `Initialize-SCuBA -Scope AllUsers`. 

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [x] Resolved all merge conflicts on branch
- [x] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [x] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by tkol2022** [comment]
@buidav Can you kindly provide some specific testing guidance on how to test the -Scope AllUsers option? For example, after I execute it, where do I check to ensure it completed as expected?

**Comment by tkol2022** [comment]
> > @buidav Can you kindly provide some specific testing guidance on how to test the -Scope AllUsers option? For example, after I execute it, where do I check to ensure it completed as expected?
> 
> This is meant for systems with multiple users. User1 and User2. Check if `Initialize-SCuBA -Scope AllUsers` installs all the ScubaGear's dependencies in a place where all users are able to access it. i.e you can run `Invoke-SCuBA` from User1 and User2.

Thanks. It sounds like we need to test on a virtual machine. Please review my testing steps below and update them if necessary.

### Testing Steps

1. Login as the user that will install Scuba: User1.
2. First make sure that Scuba is not installed. Run the command below and make sure nothing comes back
`Get-Module -Listavailable ScubaGear`

3. You can also run Invoke-Scuba and it should tell you that the cmdlet cannot be found
4. Logout
5. Login as User2. Fire up Powershell and run Invoke-Scuba without installing anything and ensure that it works.

**Review by adhilto — APPROVED** [review]
Works as expected. Testing I performed:
- Create 3 users on a VM: Alice, Bob, and an admin account.
- Run `Initialize-Scuba` as normal as Alice. Alice now has the required PowerShell modules, as expected.
- Login as Bob. Bob still does not have the required PowerShell modules, as expected.
- Login as the admin. Run `Initialize-Scuba -Scope AllUsers`. The admin now has the required PowerShell modules, as expected.
- Login as Bob. Bob now has the required PowerShell modules, as expected.

One suggestion would be to document this feature in the README, perhaps near the top of the [Dependencies](https://github.com/cisagov/ScubaGear/blob/882-should-be-possible-to-use-scope-allusers/docs/prerequisites/dependencies.md#dependencies) page. Something like "Note: the `Initialize-SCuBA` cmdlet can optionally install the required modules system-wide, if run as an administrator with `-Scope AllUsers`." Not essential, approving either way.

**Review by ehaines1 — APPROVED** [review]
I think the code looks good!

**Pull request merged**
