### PR TITLE
Fix AAD 401 authentication errors against GCC high tenants

### LINKED ISSUE #1265: AAD generates a 401 unauthorized when running against GCC High tenants
# 🐛 Summary #

We found that ScubaGear errors out with multiple 401 Unauthorized results when running the AAD provider against GCC High. After investigation, the root cause was a change to one of the Microsoft.Graph.* powershell dependency modules because we couldn't re-create the problem with older module versions. Whatever changed under the hood, now requires you to pass the FQDN when calling the Invoke-MgGraphRequest cmdlet instead of just passing a URI without the domain, particularly when you are calling a GCC High tenant. To fix this, we must pass the FQDN to Invoke-MgGraphRequest in the AAD Invoke-GraphDirectory function in ScubaGear.

image

### PR DESCRIPTION
**Pull request by tkol2022**
#  #
  

## 🗣 Description ##

This PR fixes the problem when running AAD against GCC high tenants with newer versions of the Graph dependency modules. We started getting 401 Unauthorized errors against GCC high because there was some problem with the token that we traced to Invoke-MgGraphRequest. The fix was to pass the MS graph FQDN prefix when calling that cmdlet and that seems to rectify the  issue.

Closes #1265 

## 🧪 Testing ##

- Test against all tenants, including GCC high.
- Run AAD with other products and by itself.
- Run ScubaGear with a config file as well.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by tkol2022** [comment]
Functional tests ran against the branch.

image

**Review by dagarwal-mitre — APPROVED** [review]
Looks good, checked with different tenants and SP.

**Comment by james-garriss** [comment]
FYI...the changes made to support.psm1 are in response to a previous PR (https://github.com/cisagov/ScubaGear/pull/1261) that attempted to fix a problem when initializing SG.  Unfortunately, it created a new problem with the functional tests that was only now discovered.  The changes in support fix both problems, ensuring that the right module path is used no matter where SG is initialized from.

**Comment by nanda-katikaneni** [comment]
One more data point in testing for this PR/branch: aad tests on gccchigh ran fine with this branch (with rc there 401 failure); functional tests also running fine on gcchigh with this branch.

**Pull request merged**
