### PR TITLE
Unit Test should not depend on external modules

### LINKED ISSUE #867: Unit Test (UT) should not depend on external modules
# 🐛 Summary #

A UT should be stand alone to the extent reasonable.  We have a dependency on man support module (e.g., API SDKs) in our PowerShell UT.  Refactor PowerShell UT to break the dependencies. This increases the time required to execute UT.

## To reproduce ##

1. Remove 'Inialize-SCuBA' (previously SetUp.ps1) from run_powershell_tests.yaml
1. Execute workflow, run_powershell_tests.yaml

## Expected behavior ##

What did you expect to happen that didn't?- Expect UT to pass without calling Initialize-SCuBA 
## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

### PR DESCRIPTION
**Pull request by crutchfield**
#  #
  

## 🗣 Description ##

Mock/stub all external dependencies so unit test executes without external dependencies.  Remove Setup.ps1 from run_powershell_tests.yaml.

## 💭 Motivation and context ##

Make UT more efficient and not overlap integration/functional testing. Decrease run time from 5 - 6 minutes to less than a minute +/-.
 
Closes #867 

## 🧪 Testing ##

- Execute PowerShell unit test locally 
- Execute workflow of PowerShell unit test 

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] Changes are sized such that they do not touch excessive number of files.
- [X] *All* future TODOs are captured in issues, which are referenced in code comments.
- [X] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [X] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [X] All relevant type-of-change labels added.
- [X] All relevant project fields are set.
- [X] All relevant repo and/or project documentation updated to reflect these changes.
- [X] Unit tests added/updated to cover PowerShell and Rego changes.
- [X] Functional tests added/updated to cover PowerShell and Rego changes.
- [X] All relevant functional tests passed.
- [X] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by crutchfield** [comment]
@julianjburgos @isab-m Re-baselined this feature branch due to other PR merges.

**Review by isab-m — CHANGES_REQUESTED** [review]
image
saw there was no switch statement for mock "Get-ATPProtectionPolicyRule" in Export-DefenderProvider.Tests.ps1, is that something that could be added or is there a reason why it isn't there?  

Saw that the Other warning errors for the other functions ScubaSpfRecord/DmacRecord/Dkim all have TODO statements so overlooked those warnings. 

Walked through the rest of the code and test runs, seems to be working and code looks clean.

**Comment by crutchfield** [comment]
> image saw there was no switch statement for mock "Get-ATPProtectionPolicyRule" in Export-DefenderProvider.Tests.ps1, is that something that could be added or is there a reason why it isn't there?
> 
> Saw that the Other warning errors for the other functions ScubaSpfRecord/DmacRecord/Dkim all have TODO statements so overlooked those warnings.
> 
> Walked through the rest of the code and test runs, seems to be working and code looks clean.

I was just ignoring the warnings since it was not my main focus on breaking the dependencies.  I did fix them though and now get a run without warnings - does make it look better.  Thanks!

**Review by isab-m — APPROVED** [review]

**Review by Sloane4 — APPROVED** [review]

**Comment by crutchfield** [comment]
@nanda-katikaneni  Ready for merge to main

**Pull request merged**
