### PR TITLE
OPA executable path default value inconsistent between invoke scuba with or without configfilepath

### LINKED ISSUE #875: OPAPath default value inconsistent between Invoke-Scuba invocations depending on use of -ConfigFilePath
# 🐛 Summary #

OPAPath specfifies the location of _opa_windows_amd64.exe_
OPAPath default is different depending on whether ScubaGear is invoked with -ConfigFilePath or not
This is for the location of _opa_windows_amd64.exe_

## To reproduce ##

No specific instructions to reproduce

## Expected behavior ##

If invoking without -ConfigFilePath, default location will be `$env:USERPROFILE\.scubagear\Tools`
If invoking with-ConfigFilePath, default location will be at top level directory of ScubaGear
It should invoke the same executable otherwise the versions could be out of sync.

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

### PR DESCRIPTION
**Pull request by crutchfield**
#  #
  

## 🗣 Description ##

Created ScubaDefaults to be loaded before main Scuba  module.  Refactored Invoke-Scuba and ScubaConfig to use same default value for OPA path. 

## 💭 Motivation and context ##

This is necessary to give the user a more consistent experience whether using the config file or not.
Closes #875 

## 🧪 Testing ##

- Added unit test for ScubaDefaults
- All Unit test pass
- Invoke-Scuba passes
- Invoke-Scuba -ConfigFilePath passes with no OPA path defined

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] Changes are sized such that they do not touch excessive number of files.
- [X] *All* future TODOs are captured in issues, which are referenced in code comments.
- [X] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [X] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [X] All relevant type-of-change labels added.
- [X] All relevant project fields are set.
- [X] All relevant repo and/or project documentation updated to reflect these changes.
- [X] Unit tests added/updated to cover PowerShell and Rego changes.
- [X] Functional tests added/updated to cover PowerShell and Rego changes.
- [X] All relevant functional tests passed.
- [X] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by twneale** [comment]
This all looks good to me. Should I wait for the smoke tests to pass? Or is this ok to approve? I'm new here...

**Comment by crutchfield** [comment]
> This all looks good to me. Should I wait for the smoke tests to pass? Or is this ok to approve? I'm new here...

Yes, you should wait it should pass.  I will look at it.

**Review by twneale — APPROVED** [review]
Looks good

**Comment by crutchfield** [comment]
> Might consider impact to and coordination with this open issue #835 as resolving that issue could impact how things like Get-ScubaDefaults might work and the mechanics of selecting a path for OPAExecutable if using a fallback rather than single select option.

I read the issue and tend to disagree with it.  I thin we have a single default since the user can already specify if they want it located somewhere else.  But I do believe you can add a default for OPA fallback location if 835 is implemented.

**Review by nanda-katikaneni — APPROVED** [review]
Looks good to me.

**Pull request merged**
