### PR TITLE
Fix the Handful of AAD unit tests that are broken

### LINKED ISSUE #1018: Handful of AAD unit tests are broken
# 🐛 Summary #

The AAD unit tests [listed at this link](https://github.com/cisagov/ScubaGear/pull/1001#issuecomment-2009739823) are broken and need to be fixed. This is likely due to recent changes to numerous AAD provider and Rego enhancements.

## To reproduce ##

image

### PR DESCRIPTION
**Pull request by tkol2022**
#  #
  

## 🗣 Description ##

Modified the 4 AAD unit tests that were not working - shortest description ever -- !

Closes #1018 

## 💭 Motivation and context ##

Things should not be broken.

## 🧪 Testing ##

image

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by dagarwal-mitre** [comment]
> @tkol2022 Note, to resolve Regal "line too long" annotated warnings (see in files changed view) you can either:
> 
> 1. Find a way to break the string into multiple lines such as using `concat()` and splitting the string into an array of strings with each substring on its own line, OR
> 2. If the string really needs to be that long and better exists as a single unbroken string, decorate it with a comment above the line to exempt it from Regal evaluation for that test with `# regal ignore:line-length`.

It seems like this Regal warning is coming for more lines than just the ones which Ted has changed, it might possibly be better to ignore the line-length for the entire file if possible. If not then this would require changing more lines.

**Review by dagarwal-mitre — APPROVED** [review]
Looks good, just need to address Addam's comment about Regal warnings

**Review by nanda-katikaneni — APPROVED** [review]
Looks good.

**Review by isab-m — APPROVED** [review]
Everything looks clean and tests with correct results!

**Comment by dagarwal-mitre** [comment]
@nanda-katikaneni this PR is now ready to merge, thanks!

**Pull request merged**
