### PR TITLE
Correct Erroring Default Variable Assignments on Systems with unique file paths

### LINKED ISSUE #1315: ScubaGear crashes when running OPA executable on some systems using UNC file paths
# 🐛 Summary #

When running ScubaGear on a virtual machine that is configured with \\\\UNC file paths instead of the standard C:\ I received the error message "Cannot bind to parameter 'InputObject' because it is null" and "The specified path is invalid." It also shows a path that starts with "Microsoft.Powershell.Core\FileSystem::\\\\xenprofile10" and based on my debugging the prefix before the "\\\\" is what was causing the problem. I doubt that this configuration is common in the wild because we haven't had a bug report about this before, but the fix is easy so we can correct it with little effort.

## Screenshots ##

image

## The fix ##

Screenshot of the code that is the root cause in ScubaConfig.psm1 (notice the Path field)
image

To fix this change the Path field to ProviderPath and then the DefaultOutPath won't have that Microsoft.Powershell funny business in front of it anymore.
image

### LINKED ISSUE #1369: ScubaConfig initializer exception for Invoke-SCuBA and Initialize-SCuBA
# 🐛 Summary #

When running on systems (in this cause a Debian distro) where $env:USERPROFILE is null this cryptic exception pops us.
```
`OperationStopped`: The type initalizer for `ScubaConfig` threw an exception`
```

Had to run this below to see this source error in `ScubaConfig.psm1`.
```
try {
       Initialize-SCuBA
}
catch {
   $_.Exception.InnerExecption
} 
```

Fix is to add error handling to the `DefaultOPAPath` assignment line.

Original line.
Image

The fix.
Image

## To reproduce ##
Run `Initialize-SCuBA` or `Invoke-SCuBA` on Linux and/or Macs with PowerShell 7. 

## Expected behavior ##
For ScubaGear not to throw a cryptic exception on initially running.

### PR DESCRIPTION
**Pull request by buidav**
## 🗣 Description ##

- Make  `DefaultOutPath` work on UNC file systems.
- Add a try catch to the `DefaultOPAPath` assignment. 

## 💭 Motivation and context ##

Closes #1315 
Closes #1369 

## 🧪 Testing ##

- Try to run `Import-Module .\PowerShell\ScubaGear` on a non-Windows system.
- Try to run  `Import-Module .\PowerShell\ScubaGear` on system using UNC file paths.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a ~single~ related goals ;) - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [x] Resolved all merge conflicts on branch
- [x] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [x] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by adhilto — COMMENTED** [review]
Code changes look good. Tested on a Windows, changes don't break default behavior (as expected). Deferring to @amart241 to test on a Mac.

**Comment by rmoffitt-m** [comment]
I tested this successfully on a Mac. Worked after manually installing the executable.

**Review by adhilto — APPROVED** [review]

**Review by rmoffitt-m — APPROVED** [review]
Successful test when manually downloading opa. Didn't use Install-OPAforSCuBA which seems to use a different filename (opa_darwin_amd64) but that's likely a separate issue.

**Comment by tkol2022** [comment]
I tested on a windows system using UNC paths. No errors.

image

**Pull request merged**
