### PR TITLE
Update the ScubaGear README for accuracy and add a Table of Contents 

### LINKED ISSUE #539: Update README for Basic Authentication
# 🐛 Summary #

The need for basic authentication is no longer required if the user steps up to latest setup requirements. 

## To reproduce ##

N/A

## Expected behavior ##

Update document to indicate Basic Authentication not required if updating with Setup script.  Allow for using Basic Authentication if user chooses to not step up modules

Comment from @gdasher 
README.md line 270
Suggest we change the first sentence. Given that with the latest version you no longer need to enable basic auth (right?), we should probably just instruct people to use setup.ps1 to upgrade to the version that no longer has the dependency.

### LINKED ISSUE #629: Update the README with a Table of Contents and remove any outdated sections.
# 💡 Summary #

It's been a decent amount of time since we've done a full sweep of the README. Certain sections no longer apply to ScubaGear due to PowerShell SDK updates or enhancements we made.

Also, think having a table of contents in README near the top would be a good idea as I kept having to scroll around to find certain sections. 

Could also include #539 in this update. That issue deals with updating the README to remove the basic auth directions. 

## Motivation and context ##
To keep the README updated to the current state of ScubaGear. 

## Implementation notes ##
- Adding a table of contents near the top of the README.
- Updating the README by removing outdated sections, fixing any awkward directions, etc. 
- If time/we so desire a little extra decorating.

## Acceptance criteria ##
- A table of contents is added near the top of the README.
- Outdated sections removed.

### PR DESCRIPTION
**Pull request by buidav**
#  #

## 🗣 Description ##
- Updates outdated sections in our README to what's currently accurate about ScubaGear.
- Rearranges sections to where they could better fit. 
- Adds a Table of Contents for easier navigation.
- A few formatting/grammar clean up changes. 
- Clean up in the Intro Section and add a badge for decoration. 

## 💭 Motivation and context ##

Closes #629
Closes #539 

## 🧪 Testing ##

Clicked on the links in the Table of contents to see if they were accurate.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Post-merge checklist ##

### CODE REVIEW

**Comment by mitchelbaker-cisa** [comment]
When I was first set up the project, I went through the README.md expecting to find a section outlining what information to include when creating a new pull request/issue. (something similar to `CONTENTSTYLEGUIDE.md`)

The outline below is descriptive, but I only know what to expect after clicking "New PR Request" or clicking "Get started" with either a bug report or idea. 

Screenshot 2023-11-06 110417

Maybe something similar to cisagov's development guide would make the process easier to navigate: https://github.com/cisagov/development-guide

Screenshot 2023-11-06 111957

**Review by amart241 — COMMENTED** [review]
I have been through this document a few times and everything looks to be in order. I would just like one final review with @buidav.

**Review by ssatyapal123 — CHANGES_REQUESTED** [review]
Included a few suggestions.

**Review by amart241 — APPROVED** [review]

**Review by ssatyapal123 — APPROVED** [review]
Reviewed once more and looks good!

**Comment by nanda-katikaneni** [comment]
@buidav - this branch is out of sync with main, please merge latest changes from main.

**Pull request merged**
