### PR TITLE
Revise M.S.EXO.5.1 to remove exceptional note

### LINKED ISSUE #915: Revise MS.EXO.5.1 to remove note about exceptions
# 💡 Summary #
Remove the note, "SMTP AUTH MAY be enabled on a per-mailbox basis as needed."

## Motivation and context ##
Hands-on testing has shown that SMTP AUTH cannot actually be enabled on a per-mailbox basis, despite what the documentation stating otherwise. See https://github.com/cisagov/ScubaGear/issues/607.

## Implementation notes ##
Remove both the note as well as the "(Optional) As an exception, to allow SMTP AUTH for a specific mailbox:" instructions.

## Acceptance criteria ##
- [ ] The note has been removed
- [ ] The relevant implementation steps have been removed

### PR DESCRIPTION
**Pull request by isab-m**
#  #
  

## 🗣 Description ##

Remove the note, "SMTP AUTH MAY be enabled on a per-mailbox basis as needed." and the "(Optional) As an exception, to allow SMTP AUTH for a specific mailbox:" instructions.

## 💭 Motivation and context ##

Hands-on testing has shown that SMTP AUTH cannot actually be enabled on a per-mailbox basis, despite what the documentation stating otherwise. See https://github.com/cisagov/ScubaGear/issues/607.

- closes #915

## 🧪 Testing ##

Run automated tests to ensure markdown update is syntactically correct. Run_markdown_check.yaml passes.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by adhilto — APPROVED** [review]

**Review by adhilto — CHANGES_REQUESTED** [review]
Sorry I just noticed this, but the rationale statement needs to be revised as well.
image

**Comment by isab-m** [comment]
> Sorry I just noticed this, but the rationale statement needs to be revised as well. image

Good Catch, thanks! @adhilto 
Would I need to also update the "Last modified". 
image
Also would I need to remove those resources?

**Comment by adhilto** [comment]
Good catch about the resources. You probably should remove the second resource. As to the last modified date, possibly. @ahuynhMITRE what do you think? Is this a change that would merit changing the last modified date?

**Review by nanda-katikaneni — APPROVED** [review]
Pending clarification on 'last modified date' - everything else look good to me.

**Pull request merged**
