### PR TITLE
Fix some issues with the markdown in the AAD/EntraID documentation.

### PR DESCRIPTION
**Pull request by WellKnitTech**
## 🗣 Description ##

I fixed some of the markdown that wasn't properly bolding certain items due to erroneous spaces. I also cleaned up some line ends where the bolding was overlapping the period at the end.

## 💭 Motivation and context ##

We use this tool internally so I wanted to make the documentation better.

## 🧪 Testing ##

No testing needed as I have not touched any code.

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] Changes are sized such that they do not touch excessive number of files.
## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by vinniespina — COMMENTED** [review]
i want to commit

**Review by vinniespina — COMMENTED** [review]
i commit

**Comment by ahuynhMITRE** [comment]
@mitchelbaker-cisa & @gdasher tagged you both on this small bolding update from the public to the AAD markdown for review

**Review by mitchelbaker-cisa — APPROVED** [review]
@WellKnitTech thanks for addressing the markdown issues! This PR looks good to me, we'll get it merged soon.

Smoke test fails although this is due to the PR originating from a forked repository.

**Review by gdasher — APPROVED** [review]

**Pull request merged**
