### PR TITLE
Refactor SharePoint Unit test to pull from central Jsons

### PR DESCRIPTION
**Pull request by Sloane4**
#  #
  

## 🗣 Description ##

Create central Jsons configs that can be pulled and modified slightly for each unit test
Closing #1109 

## 💭 Motivation and context ##

Reduce copy and paste errors and file size. Reduce the difficulty of writing unit tests and PRs. In the process of refactor, discovered false passing in unit tests, adding fix as closely related

## 🧪 Testing ##

- [x] All Sharepoint unit tests pass
- [x] Unit tests utilize test assertions for debugging
- [x] RunUnitTests.ps1 passes all the new utility files
image

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [x] Resolved all merge conflicts on branch
- [x] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by julianjburgos** [comment]
When running the verbose output of tests, should the Report details output a link instead of the actual HTML for a link? e.g. <a href="https://github.com/cisagov/ScubaGear/blob/vmain/PowerShell/ScubaGear/baselines/sharepoint.md#mssharepoint14v1" target="_blank">Secure Configuration Baseline policy</a>

Screenshot 2024-07-09 105817

**Comment by Sloane4** [comment]
> When running the verbose output of tests, should the Checking ReportDetails output a link instead of the actual HTML for a link? e.g. [Secure Configuration Baseline policy](https://github.com/cisagov/ScubaGear/blob/vmain/PowerShell/ScubaGear/baselines/sharepoint.md#mssharepoint14v1)
> 
> Screenshot 2024-07-09 105817

No because the output is a text statement. That only becomes a link when HTML reads it.

**Review by julianjburgos — APPROVED** [review]

**Review by adhilto — APPROVED** [review]
As always, I continue to learn more about Rego when I review your work. Looks great.

**Comment by Sloane4** [comment]
@nanda-katikaneni ready for merge

**Pull request merged**
