### PR TITLE
Update incorrect hyperlinks in SCB markdown

### LINKED ISSUE #1341: Broken markdown links
# 💡 Summary #
The following links in the markdown files are broken:
```
[{'location': '/PowerShell/ScubaGear/baselines/aad.md:75',
  'url': 'https://attack.mitre.org/techniques/T078/004/'},
 {'location': '/PowerShell/ScubaGear/baselines/aad.md:113',
  'url': 'https://attack.mitre.org/techniques/T078/004/'},
 {'location': '/PowerShell/ScubaGear/baselines/aad.md:123',
  'url': 'https://attack.mitre.org/techniques/T078/004/'},
 {'location': '/PowerShell/ScubaGear/baselines/aad.md:133',
  'url': 'https://attack.mitre.org/techniques/T078/004/'},
 {'location': '/PowerShell/ScubaGear/baselines/aad.md:267',
  'url': 'https://attack.mitre.org/techniques/T078/004/'},
 {'location': '/PowerShell/ScubaGear/baselines/aad.md:277',
  'url': 'https://attack.mitre.org/techniques/T078/004/'},
 {'location': '/PowerShell/ScubaGear/baselines/aad.md:287',
  'url': 'https://attack.mitre.org/techniques/T078/004/'},
 {'location': '/PowerShell/ScubaGear/baselines/defender.md:458',
  'url': 'https://attack.mitre.org/techniques/T1213.002/'},
 {'location': '/PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/aad.md:204',
  'url': 'https://playbooks.idmanagement.gov/piv/network/group/'}]
```

## Motivation and context ##
We don't want our users to run into 404 errors from our documentation.

## Implementation notes ##
All but the last give 404 errors. The last one gives a certificate error. The last one isn't user facing so is less important, but if we were ever to add the capability to validate the markdown links to the CI/CD pipeline (something I'm exploring right now), it would be worth correcting.

## Acceptance criteria ##
- [ ] The links have been corrected

### PR DESCRIPTION
**Pull request by ahuynhMITRE**
## 💭 Motivation and context ##

Updated the broken markdown links that were causing 404 errors. 
Closes #1341 

## 🧪 Testing ##

validate that the broken links listed in the issue have been updated and no 404 issues occur.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [x] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by adhilto — COMMENTED** [review]
This corrects all but the last link listed in issue #1341, "https://playbooks.idmanagement.gov/piv/network/group/" in "/PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/aad.md".  @ahuynhMITRE I'm assuming you'd rather scope this PR to just baseline changes? If so, I'd recommend opening a second issue to track that final link. It's a low priority thing, I just don't want to lose track of it.

**Comment by ahuynhMITRE** [comment]
> This corrects all but the last link listed in issue #1341, "https://playbooks.idmanagement.gov/piv/network/group/" in "/PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/aad.md". @ahuynhMITRE I'm assuming you'd rather scope this PR to just baseline changes? If so, I'd recommend opening a second issue to track that final link. It's a low priority thing, I just don't want to lose track of it.

yep will separate into a a new issue so it doesn't get lost! thanks for the reminder @adhilto!

**Comment by ahuynhMITRE** [comment]
@nanda-katikaneni good to merge!

**Comment by ahuynhMITRE** [comment]
> > This corrects all but the last link listed in issue #1341, "https://playbooks.idmanagement.gov/piv/network/group/" in "/PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/aad.md". @ahuynhMITRE I'm assuming you'd rather scope this PR to just baseline changes? If so, I'd recommend opening a second issue to track that final link. It's a low priority thing, I just don't want to lose track of it.
> 
> yep will separate into a a new issue so it doesn't get lost! thanks for the reminder @adhilto!

new issue #1421 created to capture the remaining link certificate error!

**Pull request merged**
