### PR TITLE
Modify MS.AAD.6.1 to account for federated domains

### LINKED ISSUE #1080: MS.AAD.6.1 Does not account for federated domains
# 🐛 Summary #

What's wrong? Please be specific.
Any federated domains do not have the fields:
 passwordNotificationWindowInDays
 passwordValidityPeriodInDays

**Note for whoever gets assigned this issue**: refer to the [instructions in this comment](https://github.com/cisagov/ScubaGear/issues/1080#issuecomment-2086346747) for the code changes needed.

## To reproduce ##

Run Get-MgBetaDomain against a tenant with federated domains (ADFS).

## Expected behavior ##

The password policy is enforced locally, an exception for any federated domains would do the trick.

## Any helpful log output or screenshots ##

Paste the results here:

```console

{
  "id": "generic.domain.com",
  "authenticationType": "Federated",
  "isAdminManaged": true,
  "isDefault": false,
  "isInitial": false,
  "isRoot": false,
  "isVerified": true,
  "supportedServices": [ "Email", "OfficeCommunicationsOnline", "OrgIdAuthentication", "Intune" ]
}

```

Add any screenshots of the problem here.

### PR DESCRIPTION
**Pull request by mitchelbaker-cisa**
#  #
  

## 🗣 Description ##

Modified the rule for MS.AAD.6.1 such that federated domains are excluded from the check. Only domains with AuthenticationType = "Managed" will be considered. 

That being said, detailed reporting is expanded to indicate to the user if federated domains are present. Users should refer to their identity provider on how to configure these domains in a federated context. 

Screenshot (115)

## 💭 Motivation and context ##

Resolves #1080 

## 🧪 Testing ##

From .\Testing run 
```
.\RunUnitTests.ps1 -p aad -c 6
```

To run functional tests copy/paste into a PS script: 

```
$TestContainers = @() 
$TestContainers += New-PesterContainer -Path "Testing/Functional/Products" `
-Data @{ 
    Thumbprint = "<thumbprint>"; 
    TenantDomain = "<domain>"; 
    TenantDisplayName = "<display-name>"; 
    AppId = "<app-id>"; 
    ProductName = "aad"; 
    M365Environment = "gcc"
} 
$PesterConfig = @{
        Run = @{Container = $TestContainers}
        Filter = @{Tag = @("MS.AAD.6.1v1")}
        Output = @{Verbosity = 'Detailed'}
    }

$Config = New-PesterConfiguration -Hashtable $PesterConfig 
Invoke-Pester -Configuration $Config
```

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by tkol2022** [comment]
@mitchelbaker-cisa your unit test for AAD policy 3.2 was failing the unit test so I looked into it. I compared your AAD Rego code to main and you are out of synch. Need to rebase maybe.

image

**Comment by mitchelbaker-cisa** [comment]
@tkol2022 Thanks for catching that, must have slipped through when rebasing. Reverted so it matches main.

**Comment by tkol2022** [comment]
Upon reviewing the Rego code I performed some hands-on tests with update-MgBetaDomain to ensure that the value of Int Max 2147483647 is the correct value in the API to represent the "Set passwords to never expire" setting. I tried setting the parameter PasswordValidityPeriodInDays to 0 and -1 and the system did not allow me to do so. I also examined verified that the value coming from the API will be 2147483647 when the user sets password to not expire in the admin portal.

**Comment by tkol2022** [comment]
I created and verified a new M365 domain to determine how the password expiration gets treated.
Looks like by default, Microsoft sets the PasswordValidityPeriodInDays to 2147483647 which is "password does not expire".
This is more credence that the coding approach used here looks solid.

image
image

**Comment by tkol2022** [comment]
@mitchelbaker-cisa I ran a test that produced this TestResults.json. Can you verify that this ActualValue field is what you expect? I also recommend that we put a comment in the Rego explaining why you put said values into that field.

For policy 6.1 the ActualValue field contains a couple of nested arrays. The first one is empty. The second one contains these two domains:
Domain 1 - This domain is not compliant because it has a password expiration date.
Domain 2 - This domain is compliant because it does not.

image
image

**Comment by tkol2022** [comment]
In the report message, when Federated domains are detected, I'm thinking we should explicitly state that we cannot read the policy values for the password expiration because it is controlled in a system that is external to the tenant or something along these lines. This is to be crystal clear that we didn't pass or fail domains that are Federated - we simply can't examine them.

image

**Comment by tkol2022** [comment]
This is regarding the unit tests.
Based on my testing of the API, it will not accept values for the password expiration that are negative, 0 or over INTMAX so I would update your test cases to simply have some non negative value which would reflect real world scenarios more closely. You currently have some of them set to 0.

image

**Review by tkol2022 — APPROVED** [review]
I put some comments. Based on testing the code seems to behave as expected.
Nice job !

**Review by Sloane4 — APPROVED** [review]

**Comment by mitchelbaker-cisa** [comment]
@tkol2022 I addressed your comments regarding the following:
- add a comment providing rationale behind the content of ActualValue and include FederatedDomains value.
- explicitly stating we cannot read the policy values for password expiration for federated domains; below is the updated warning.
Screenshot (134)
- adjust unit/functional test values for "PasswordValidityPeriodInDays" to a non negative value.

**Comment by mitchelbaker-cisa** [comment]
@nanda-katikaneni ready to merge

**Pull request merged**
