### PR TITLE
Integrate review feedback into Defender baseline

### LINKED ISSUE #533: Integrate CISA review feedback into Defender baseline
# 💡 Summary #

CISA formal review will provide feedback that may require changes to the markdown formatted Defender baseline.

## Motivation and context ##

CISA formal review may discover changes that materially affect the baselines.  If changes are made, they should be reflected in the markdown baselines as the source of truth for secure configuration baselines.

## Implementation notes ##

Please provide details for implementation, such as:

- Review CISA feedback in terms of suggested changes and comments
- Adjudicate comments with CISA to confirm recommended changes
- Make recommended changes to the markdown baselines

## Acceptance criteria ##

How do we know when this work is done?

- [x] CISA feedback on Defender SCB has been received by the developers
- [ ] All CISA feedback has been reviewed and changes recommended and adjudicated successfully
- [ ] Changes have been integrated into Defender markdown and merged into Emerald branch

### PR DESCRIPTION
**Pull request by schrolla**
#  #

## 🗣 Description ##

This update includes the following changes to the M365 Defender security configuration baseline:

- Changes to improve overall consistency of format and language throughout
- Grammar and spelling fixes
- Language and verbiage updates for increased reader clarity

This update does NOT include any materially significant changes to the number of or content in policy items in the baseline itself that would require a change in settings to align with the baseline recommendations.

## 💭 Motivation and context ##

The updates included further refine and improve the overall readability and clarity of the baseline document.  The result should be a baseline that is easier to interpret and use as a reference for M365 tenant administrators.

Closes #533 

## 🧪 Testing ##

Compare the separately provided Word version with track changes of the Defender baseline document with the changes in the markdown in this branch.  Accepted/modified suggested changes as appropriate and mirrored in markdown, rejected and additional changes commented in Word and sync'd to markdown as needed.

Manual review of markdown and ensure that the automated markdown test on the PR passes.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Rebase the branch against the parent branch prior to merge as needed.
- [ ] All CISA feedback has been reviewed and adjudicated successfully

## ✅ Post-merge checklist ##

- [ ] Confirm that the parent branch passes all tests after the merge

### CODE REVIEW

**Comment by tkol2022** [comment]
@ahuynhMITRE Please follow all hyperlinks to ensure that they work appropriately including between sections of the document.

**Review by ahuynhMITRE — APPROVED** [review]
no further comments after the update to the front-matter

**Comment by tkol2022** [comment]
Looks like an incorrect policy identifier in the criticality field for 4.4.

@crutchfield Is there a tool in our automation arsenal that should be catching this?

image

**Comment by tkol2022** [comment]
Standardize the use of either apps or applications.

image

**Comment by crutchfield** [comment]
> Looks like an incorrect policy identifier in the criticality field for 4.4.
> 
> @crutchfield Is there a tool in our automation arsenal that should be catching this?
> 
> image

It is not checked today.  We shoud add to the appropriate place in the run_markdown_check.yaml (based on unit test).  Probally can be part of work to start using the criticallity from baseline documents instead of hard coded values in Rego.

**Comment by tkol2022** [comment]
6.2 Resources, last hyperlink, the titles between markdown versus Word do not match.

image
image

**Pull request merged**
