### PR TITLE
Initial Automated Functional Test Orchestrator

### LINKED ISSUE #419: Implement automated functional test for AAD
# 💡 Summary #

Provide an automated functional test for all policies defined in the AAD secure baseline.  

## Motivation and context ##

Provides project with an automated, repeatable test plan for AAD.  
Reduces 'touch' labor for testing.

## Implementation notes ##
Use data driven test approach. 
Organize test plan by Policy (i.e., Policy Id)
Generate Pass/Fail test cases where appropriate
Allow manual/automated execution

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Execute functional test for AAD and verify expected results

### PR DESCRIPTION
**Pull request by crutchfield**
#  #

## 🗣 Description ##

Initial code drop of a functional test orchestrator.  The orchestrator allows for a YAML input describing a test of test cases grouped by policy Id.  The tester can select either a RunScuba or RunCached test driver depending on needs. 

## 💭 Motivation and context ##

The change is needed to facilitate the capture (e.g., in YAML) test plans for each product.  The orgistrator will allow these to be automatically executed either automatically or with limited interaction.  This should reduce our test burden.

closes #419 

## 🧪 Testing ##
#Set up selenium
## Setup Selenium & Driver
Install-Module Selenium
Import-Module Selenium
$WebDriversPath = Join-Path -Path (Get-Module Selenium).ModuleBase -ChildPath "assemblies"
.\Testing\Functional\SmokeTest\UpdateSelenium.ps1 -webDriversPath $WebDriversPath

Replace with your credentials. 
``` code
$TestContainers = @()
$TestContainers += New-PesterContainer -Path "Testing/Functional/Products" -Data @{ Thumbprint = "04C04809CC43AF66D805399D09B69069041574B0"; TenantDomain = "y2zj1.onmicrosoft.com"; TenantDisplayName = "y2zj1"; AppId = "9947b06c-46a9-4ff2-80c8-27261e58868a"; ProductName = "aad"; M365Environment = "commercial" }
Invoke-Pester -Container $TestContainers -Output Detailed
```

## 📷 Screenshots (if appropriate) ##
image

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [X] All relevant type-of-change labels have been added.
- [X] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [X] Tests have been added and/or modified to cover the changes in this PR.
- [X] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Comment by Dylan-MITRE** [comment]
Some minor PS Linter needed to be fix for UpdateSelenium.ps1

**Review by tkol2022 — APPROVED** [review]
I tested this code extensively to create AAD and EXO functional test YAML files. Crutch added some functionality to cover cases that were not initially supported. Works excellent.

**Review by ssatyapal123 — COMMENTED** [review]
I reviewed the aad.testplan.yaml and thought it was comprehensive and will be most helpful for testing. Here are some minor comments and suggestions which may be useful for the next iteration:
- Consider adding header comment describing each test scenario
- Curious why 1.1 does not use the Splat syntax
- For 2.1, 2.3, and 3.2 why check for Report-Only as non-compliant condition? Is it worth adding a test case for the setting being checked for that baseline (e.g., High risk users are/are not being blocked?)
- Consider adding test scenario for Legacy Authentication “not blocked” status in addition to the check for client app type
- Consider adding a comment to highlight the field that is being assessed for compliance by each test scenario
- The convention of using “Compliant” and “Non-compliant” in Test Description is not used for MS.AAD.2.3v1
- Consider adding a description to MS.AAD.3.1v1 Compliant Case
- 3.2v1 missing the test case where an alternative MFA is used
- 5.2v1 tests are included twice
- 5.4v1 tests seem to be included twice
- 7.8 and 7.9 seem to be testing the same conditions

**Comment by crutchfield** [comment]
> * Consider adding header comment describing each test scenario

@ssatyapal123 Please elaborate a little on this.  My assumption is you are suggesting we treat TestDescription as a short/abbriviated title/description and add a place for a more comprehensive description to be added in teh YAML file.  Maybe change TestDescription into two items;  Title and Dscription

**Comment by crutchfield** [comment]
> * Curious why 1.1 does not use the Splat syntax

Please clarify.  I might not understand the question. 

image

**Comment by crutchfield** [comment]
@ssatyapal123 
For 2.1, 2.3, and 3.2 why check for Report-Only as non-compliant condition? Is it worth adding a test case for the setting being checked for that baseline (e.g., High risk users are/are not being blocked?)

Concur.  Additional test cases should be added.  Report only check is neccesary but not sufficent.

**Comment by crutchfield** [comment]
> * Consider adding test scenario for Legacy Authentication “not blocked” status in addition to the check for client app type

Added test case, MS.AAD.1.1v1 Non-Compliant case - not blocked (approvedApplication).

image

**Comment by crutchfield** [comment]
> * Consider adding a comment to highlight the field that is being assessed for compliance by each test scenario

@ssatyapal123 Is your intent that this be strictly a test plan (i.e., YAML) artifact?  Or does this flow through the actual test to be reported.  If the former, we can already accomidate.  We can 1) Add a Comment field at the top level or if we split TestDescription into Title & Description then the more descriptive "description" field could high light what is being tested.

**Comment by crutchfield** [comment]
> * The convention of using “Compliant” and “Non-compliant” in Test Description is not used for MS.AAD.2.3v1

Updated with Compliant/Non-compliant

**Comment by crutchfield** [comment]
@ssatyapal123 
> * Consider adding a description to MS.AAD.3.1v1 Compliant Case

Added description, "MS.AAD.3.1v1 Compliant case - Phishing-resistant MFA enabled"

**Comment by crutchfield** [comment]
@ssatyapal123 
> * 3.2v1 missing the test case where an alternative MFA is used

I think this test case, MS.AAD.3.2v1 Compliant case - Non specific MFA method is enforced, is suppose to cover alternative MFA.

**Comment by crutchfield** [comment]
@ssatyapal123 
> * 5.4v1 tests seem to be included twice
Removed duplicate

**Comment by crutchfield** [comment]
@ssatyapal123 
> * 7.8 and 7.9 seem to be testing the same conditions

It looks to me that the conditionas are similar but the policys are distinct.  7.8 looks strictly at Global Admin while 7.9 checks "other" privileged roles.  @tkol2022 You have thoughts?

**Comment by crutchfield** [comment]
@ssatyapal123 
> * 7.8 and 7.9 seem to be testing the same conditions

It looks to me that the conditionas are similar but the policys are distinct.  7.8 looks strictly at Global Admin while 7.9 checks "other" privileged roles.  @tkol2022 You have thoughts?

**Review by ssatyapal123 — APPROVED** [review]
Reviewed exo.testplan.yaml and looks good although I'm not as familiar on the tests as for aad. A couple of comments/questions:
- Only 7.1v1 included comments beneath the preconditions and postconditions
- Are the baselines that are commented out (e.g., 8.1) still to be done or are they manual checks that can't be automated?

**Comment by crutchfield** [comment]
> Reviewed exo.testplan.yaml and looks good although I'm not as familiar on the tests as for aad. A couple of comments/questions:
> 
> * Only 7.1v1 included comments beneath the preconditions and postconditions
> * Are the baselines that are commented out (e.g., 8.1) still to be done or are they manual checks that can't be automated?

@ssatyapal123  The yaml format will accept comments.  I suppose it is good practise to add comments if the test case needs amplifications.  I uncommented the test cases and pushed to baseline.  Suspect they were commented out to save testing time .

**Comment by crutchfield** [comment]
@nanda-katikaneni PR is ready to merge into Emerald

**Pull request merged**
