### PR TITLE
Sharepoint 1.3 to check domain and security group & 1.4 to check the same account for external sharing

### PR DESCRIPTION
**Pull request by Dylan-MITRE**
## 🗣 Description ##

Sharepoint 1.3 domains n security groups (currently not implemented) but mention that in the report
Sharepoint 1.4 to check Guests must sign in using the same account to which sharing invitations are sent.

## 💭 Motivation and context ##

- Matches with the current baseline update
- Indicated that we are not currently pulling information on security group for 1.3 in the report
- New 1.4 to check 
- closing #480 
- closing #523 
- closing #568 

## 🧪 Testing ##

Code changed in:
- Unit test 
- Rego

Run Sharepoint and observe 1.3 n 1.4 to make sure they work as intended

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

### CODE REVIEW

**Comment by tkol2022** [comment]
Please prioritize the testing of this pull request because we are working on the automated functional tests and we finished Sharepoint but have to modify it based on this code update.

When testing, please run at least a few different compliant and non-compliant scenarios and ensure that the report produces the correct result according to the how the policy was updated.
Thanks!

**Review by ssatyapal123 — APPROVED** [review]
Tested and verified successfully (positive and negative results) against G3, E5, and G5 tenants with different combinations.

**Comment by Dylan-MITRE** [comment]
> Didn't realize I was reviewer on this. Here are some minor text suggestions.

Thank you! changes has been made.

**Comment by Dylan-MITRE** [comment]
> More of question. If we leave the list of allowed external domains for SharePoint 1.3 blank then the policy check fails. Is this by design or are users not allowed to leave the list to be empty?
> 
> Empty List emptyList
> 
> Failing on the HTML report. sharepointFail

yea so basically when you leave it empty Microsoft treat the box as unchecked.

**Comment by crutchfield** [comment]
@Dylan-MITRE Is MS.SHAREPOINT.1.5v1 still needed in the rego?  It appears to have been removed from the SCB.  I opened an issue on it as dead code (while writing functional test plan) #568.  Perhaps it should be addressed in this PR.

**Comment by Dylan-MITRE** [comment]
> @Dylan-MITRE Is MS.SHAREPOINT.1.5v1 still needed in the rego? It appears to have been removed from the SCB. I opened an issue on it as dead code (while writing functional test plan) #568. Perhaps it should be addressed in this PR.

its removed now

**Review by nanda-katikaneni — APPROVED** [review]
Tested on the G5 and E5 tenants works fine; no new comments based on code review. Approving.

**Pull request merged**
