### PR TITLE
Fix encoding issue by removing BOM from provider output files

### LINKED ISSUE #935: OPA output function fails due to escape sequence
# 🐛 Summary #
Gets a Fatal Error involving the OPA output function.

What's wrong? Please be specific.

## To reproduce ##
Invoke-SCuBA -OPAPath "C:\Temp\ScubaGear\" -ProductNames aad -OutPath "C:\XX\"

## Expected behavior ##
Expected a report

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

The script fails with this error:
Fatal Error involving the OPA output function.
            Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter '
InputObject' because it is null.
At C:\Temp\ScubaGear\PowerShell\ScubaGear\Modules\Orchestrator.psm1:697 char:13
             throw $InvokeRegoErrorMessage
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : OperationStopped: (Fatal Error inv...use it is null.:String) [], RuntimeException
     FullyQualifiedErrorId : Fatal Error involving the OPA output function.
                Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter 'InputObject' because it is null.


It creates a ProviderSettingsExport.json as only output file,

### LINKED ISSUE #990: Defender errors when running against  DLP policies with \. And \T syntax
# 🐛 Summary #

What's wrong? Please be specific.

An agency has noted that when running the Invoke-Scuba command the PowerShell failed with no results. Attached below are the errors in the PowerShell terminal and were not specific to DLP however through additional investigation and testing two of the DLP compliance policies (attached) contained the following syntax  “\.” and “\T” causing the error. Once the two policies were removed/renamed the script ran successfully. 

## To reproduce ##

1. Create DLP compliance policies including the syntax included in the attachments and linked above
2. Run ScubaGear

## Expected behavior ##

Expectation: ScubaGear to run and capture the DLP compliant policies for the defender product

## Any helpful log output or screenshots ##

PowerShell Error:
PowerShell Error

Syntax from Provider Export:
ProviderSettingsExport-DLPSyntaxError-1

ProviderSettingsExport-DLPSyntaxError-2

### LINKED ISSUE #1138: Ensure robust escape handling for ScubaGear inputs
# 💡 Summary #

Several reports of ScubaGear erroring out have been received and the common thread appears to be tenants that contain escaped values or '\' characters, such as in file paths, within various tenant fields (e.g. policy names).  The goal is to investigate and develop a solution to address the general escaping issue rather than patch specific reported instances.

## Motivation and context ##

Escaped values exist in the wild and need to be handled properly by ScubaGear.

## Implementation notes ##

Please provide details for implementation, such as:

- Review existing bug reports of escape handling issues and existing analyses
- Research options to resolve more generally
- Implement fix and test against existing bug reports

## Acceptance criteria ##

The following issues are completed

- [x] Escaped values are successfully handled and rendered by ScubaGear
- [ ] Issue #990 is resolved
- [ ] Issue #935 is resolved
- [ ] Issue #1214 is resolved
- [ ] Issue #1242 is resolved

### LINKED ISSUE #1214: unable to parse input: yaml: line 1136: found unknown escape character (Defender)
# Problem with JSON parsing #

There is an issue when generating report for a **Defender**:

```Powershell
Invoke-SCuBA -OPAPath "C:\Temp\ScubaGear\" -ProductNames defender -OutPath "C:\Temp\ScubaGear"

unable to parse input: yaml: line 1136: found unknown escape character
Fatal Error involving the OPA output function.
            Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\ScubaGear\1.3.0\Modules\Orchestrator.psm1:736 char:13
+             throw $InvokeRegoErrorMessage
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Fatal Error inv...use it is null.:String) [], RuntimeException
    + FullyQualifiedErrorId : Fatal Error involving the OPA output function.
            Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter 'InputObject' because it is null.
```

Offending lines in  **ProviderSettingsExport.json** are **1136**,**1137**:

```json
"Identity":  "FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/<tenant>.onmicrosoft.com/Configuration/PESEL sharing (Sharepoint\Onedrive, alert \u003e= 10)",
"Id":  "FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/<tenant>.onmicrosoft.com/Configuration/PESEL sharing (Sharepoint\Onedrive, alert \u003e= 10)",
```

**Solution**

To workaround this problem you need to use method mentioned by [adhilto](https://github.com/adhilto) in [#807](https://github.com/cisagov/ScubaGear/issues/807#issuecomment-1899765241):

1. Run Import-Module .\PowerShell\ScubaGear from the main folder of the repo.
2. Run  Invoke-RunCached -p defender -OutPath example. The same error you ran into before will occur.
3. Open the ProviderSettingsExport.json file within the example folder and correct the json error. 

In my case I had to change:

```text
\ -> \\
 ```

in

```text
Sharepoint\Onedrive -> Sharepoint\\Onedrive
```

4.  Run Invoke-RunCached -p defender -OutPath example -ExportProvider $false. ScubaGear will run using the modified json file, allowing you to bypass the bug until we work out a fix.

### LINKED ISSUE #1242: unable to parse input: yaml: line 3902: found unknown escape character
# 🐛 Summary #

What's wrong? Please be specific.
There seems to be an error at line 3902 but it's not present in the Orchestrator file.

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?
The script can run for aad, sharepoint, teams and exo but fails for defender

## Any helpful log output or screenshots ##

Paste the results here:

unable to parse input: yaml: line 3902: found unknown escape character
Fatal Error involving the OPA output function.
            Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter
'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\ScubaGear\1.3.0\Modules\Orchestrator.psm1:735 char:13
+             throw $InvokeRegoErrorMessage
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Fatal Error inv...use it is null.:String) [], RuntimeException
    + FullyQualifiedErrorId : Fatal Error involving the OPA output function.
                Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parame
   ter 'InputObject' because it is null.
Add any screenshots of the problem here.

### LINKED ISSUE #1299: Error with OPA parsing, only for Defender
I am receiving the following error when trying to run the Defender module.  Based on what I see in Issue 935, this may be the same bug.  All other modules function. 

PS C:\Users\redacted> Invoke-Scuba -ProductNames defender
unable to parse input: yaml: line 163: found unknown escape character
Fatal Error involving the OPA output function.
            Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter
'InputObject' because it is null.
At C:\Users\redacted\Documents\WindowsPowerShell\Modules\ScubaGear\1.3.0\Modules\Orchestrator.psm1:735
char:13
+             throw $InvokeRegoErrorMessage
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Fatal Error inv...use it is null.:String) [], RuntimeException
    + FullyQualifiedErrorId : Fatal Error involving the OPA output function.
                Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter 'InputObject' because it is null.

Here are the lines in and around 163 in the ProviderSettingsExport.json:

        "PolicyRBACScopes":  [

                             ],
        "Identity":  "FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/redacted.onmicrosoft.com/Configuration/M365 DLP Policy 08\04\2022",
        "Id":  "FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/redacted.onmicrosoft.com/Configuration/M365 DLP Policy 08\04\2022",
        "IsValid":  true,
        "ExchangeVersion":  "0.20 (15.0.0.0)",

### PR DESCRIPTION
**Pull request by schrolla**
#  #
  

## 🗣 Description ##

This update changes ScubaGear such that its tenant configuration captured in the provider output JSON (ProviderSettingsExport.json, by default) is encoded as a UTF-8 file without a byte order mark (BOM) rather than including a BOM.  

Updates to the code include:
 * New functions Get-Utf8NoBOM and Set-Utf8NoBOM for reading and writing utf-8 encoded files without a BOM
 * Wrapper functions Invoke-ReadAllLines and Invoke-WriteAllLines that provide testability for use of the associated .NET System.IO functions
 * A new Utility powershell module for the above functions to support use across ScubaGear modules
 * PowerShell unit tests for the new methods covering pathing and escape sequence handling

## 💭 Motivation and context ##

OPA Rego (as of 0.68) does not recognize the byte order mark (BOM).  As a result, parsing of the file can fail when some character sequences, such as unescaped backslashes, are present in the input.  These characters are common in certain tenant configurations, such as Exchange transport rule regular expressions or Windows file paths.  By removing the BOM from provider output files and encoding as UTF-8 without a BOM, Rego can properly handle the provider JSON as input without issue.

Closes #935
Closes #990 
Closes #1138 
Closes #1214
Closes #1242
Closes #1299

## 🧪 Testing ##

To test this PR, first configure a test tenant such that it contains an input that triggers the existing bug.  This can be done by adding or modifying an existing DLP policy description to include the string:
```Create a "\/Date(1698260458733)\/" custom policy from )\/scratch. You "\/Date will choose the type of content to protect and how you want to protect it.```

Run ScubaGear against the test tenant including the Defender product, at a minimum.
``` Invoke-Scuba -p defender ```

This should result in an error similar to the one shown here:
image

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [x] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by adhilto — APPROVED** [review]
Looks great. Testing I performed:
- I tested against 4 different tenants, it worked as expected in all cases.
- I tested naming a conditional access policy `\/ \A \B Ĥ \` to see how it handled backslashes and unicode, it also worked as expected.
- I tested with a non-default OutPath, also worked as expected
- Finally, I tested `Invoke-ScubaCached` to see if it could read BOM-less json, worked as expected.

One minor comment left below, also the PSLinter is unhappy about `Write-Host`. Both things are minor enough, would like to see them addressed, but approving either way.

**Comment by tkol2022** [comment]
### Comments on usage of specific System.IO.File methods

- Can you use WriteAllText instead of WriteAllLines? WriteAllText takes a string as the contents argument instead of an array of strings.
- Can you use ReadAllText instead of ReadAllLines? Same reason as prior bullet.

I tried making these changes and it seemed to work okay but you should do some testing.

I also ran some limited benchmark time comparisons between WriteAllText versus WriteAllLines and didn't see any difference. Regardless I think using the *AllText versions make sense.

Time when using WriteAllText 
image


Time when using WriteAllLines 
image

**Comment by tkol2022** [comment]
Tested on a Windows system that uses \\\\UNC paths and the fix code works fine.

**Comment by tkol2022** [comment]
### Tests of various strings and escape characters
Conducted tests with the data described below against the E5 tenant. No defects found yet.

### Defender DLP Policy comment field
#### Generally ugly test string
This is a non-escaping comment. αۂ a \"\\/Date(1698260458733)\\/\" custom policy from )\\/scratch.\nYou \"\\/Date will choose \\ the type of content\\u0000 to protect and how you want to protect it.\\\"   tabs\\t, newlines\\n, or \\uD83D\\uDE00 emoji 😀 for testing. Special JSON characters: { "key\": \"value\" } and SQL injection: '; DROP TABLE users; --'

#### Emoji test string
🧬🦠🧫🧪🛸🤖🦾🦿🧍‍♂️🧍‍♀️🧑‍🤝‍🧑🦹‍♂️🦹‍♀️🦸‍♂️🦸‍♀️🧙‍♂️🧙‍♀️🧛‍♂️🧛‍♀️🧜‍♂️🧜‍♀️🧞‍♂️🧞‍♀️🧝‍♂️🧝‍♀️🧟‍♂️🧟‍♀️🦧🦣🦦🦨🦩🦫🦭🦬🦙🦘🦡🦔🦏🦈🦭🦅🦩


### Exchange transport rule Regex
^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$|^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$|^user[A-Z0-9]+$

### Exchange transport rule name
αۂ a \"\\/Date(1698260458733)\\/\" custom policy
\/Date(1695680803000)\/
"\/Date(1695680803000)\/"
\\\\\\\\\\\\\

### Exchange transport rule comment
𝖘𝖚𝖕𝖊𝖗⚡𝖈𝖔𝖒𝖕𝖑𝖊𝖝🚀𝖓𝖆𝖒𝖊❗✨ NullChar:\0 Backspace:\b BellChar:\a ZeroWidthSpace:\u200B ByteOrderMark:\uFEFF💣

[Also pasted an HTML document into the comment which I have redacted here for brevity]

**Comment by tkol2022** [comment]
Tested on a Windows system running ScubaGear in a OneDrive folder and the fix code works fine.

**Comment by tkol2022** [comment]
In your Get-Utf8NoBom.Tests.ps1, can you use the approach below to avoid hard coding the C$ or does this not matter? I added the $SystemDrive variable.

```
Context 'UNC path' {
            It 'Set to shared UNC path' {
                $SystemDrive = $(Resolve-Path $TestDrive).ProviderPath.Substring(0, 1)
                $TempFolder = $($(Resolve-Path $TestDrive).ProviderPath).Substring(2)
                $TestFile = "\\$env:COMPUTERNAME\$SystemDrive$\$TempFolder\output.json"
                New-Item -ItemType File $TestFile
                Get-Utf8NoBom -FilePath $TestFile | Should -Be "Pass"
            }
        }
```

**Comment by tkol2022** [comment]
Recommendation to consider. For consistency, in the Set-Utf8NoBom.Tests.ps1 first set of tests, tweak the declaration of the mock function Invoke-WriteAllText as per below. I found this easier to read.

```
BeforeAll {
            Mock -ModuleName Utility Invoke-WriteAllText { }

            # Setup test directories for testing
            Push-Location $TestDrive
            New-Item -ItemType Directory "$TestDrive\a\b" -Force -ErrorAction Ignore
            New-Item -ItemType Directory "$TestDrive\c" -Force -ErrorAction Ignore
        }
```

This also helps make the code consistent with how you declared the mock function in the sister file Get-Utf8NoBom.Tests.ps1
image

**Comment by tkol2022** [comment]
I couldn't tell the difference between the 'Set-Utf8NoBom Inputs' versus 'Get-Utf8NoBom Inputs' unit tests. They look identical?

image

**Review by tkol2022 — APPROVED** [review]
Completed my review / testing and left some parting comments on the unit tests. Minor tweaks. Creative work on the unit tests. Nice job overall and good teamwork with @adhilto

**Pull request merged**
