### PR TITLE
Remove an unnecessary cmdlet from aad policy check 5.3 to improve performance of the provider

### LINKED ISSUE #729: Remove an unnecessary Cmdlet from AAD policy check 5.3 to improve performance of the provider
# 💡 Summary #

For Rego policy check 5.3 we can **replace Get-MgBetaPolicyAdminConsentRequestPolicy and use Get-MgBetaDirectorySetting instead**. We already use Get-MgBetaDirectorySetting for policy 5.4 so we can remove the extra cmdlet Get-MgBetaPolicyAdminConsentRequestPolicy from the provider to make AAD run faster.
When developing the functional test cases for AAD I discovered that the Get-MgBetaDirectorySetting returns a field named EnableAdminConsentRequests that we can check to see if the admin consent workflow is enabled. 

In addition to updating the Rego policy check, updating the functional test case yaml code is part of the scope of this issue.
Below I have included a draft functional test case that references the Get-MgBetaDirectorySetting / Update-MgBetaDirectorySetting cmdlets and the EnableAdminConsentRequests field.

```
 - PolicyId: MS.AAD.5.3v1
   TestDriver: RunScuba
   Tests:
     - TestDescription: MS.AAD.5.3v1 Compliant - Users can request admin consent to apps they are unable to consent to
       Preconditions: 
         - Command: UpdateDirectorySettingByName
           Splat:
             DisplayName: Consent Policy Settings
             Updates:
               BodyParameter:
                 Values:
                   - Name: EnableAdminConsentRequests
                     Value: true
       Postconditions: []
       ExpectedResult: true
```

## Acceptance criteria ##

- [x] Provider code has been updated to remove the unnecessary Cmdlet
- [x] Rego policy code has been updated
- [x] Rego unit tests have been updated
- [x] Functional test case has been updated
- [x] All code and functional test have been functionally tested against the test tenants

### PR DESCRIPTION
**Pull request by crutchfield**
#  #
  

## 🗣 Description ##
For Rego policy check 5.3 we can replace Get-MgBetaPolicyAdminConsentRequestPolicy and use Get-MgBetaDirectorySetting instead. We already use Get-MgBetaDirectorySetting for policy 5.4 so we can remove the extra cmdlet Get-MgBetaPolicyAdminConsentRequestPolicy from the provider to make AAD run faster.
When developing the functional test cases for AAD I discovered that the Get-MgBetaDirectorySetting returns a field named EnableAdminConsentRequests that we can check to see if the admin consent workflow is enabled.

## 💭 Motivation and context ##

Increase performance of ScubaGear
closes #729 

## 🧪 Testing ##

- Ran UT, passed
- Ran FT for AAD, passed
- Ran Invoke-Scuba against tenant and got expected results. 

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] Changes are sized such that they do not touch excessive number of files.
- [X] *All* future TODOs are captured in issues, which are referenced in code comments.
- [X] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [X] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [X] All relevant type-of-change labels added.
- [X] All relevant project fields are set.
- [X] All relevant repo and/or project documentation updated to reflect these changes.
- [X] Unit tests added/updated to cover PowerShell and Rego changes.
- [X] Functional tests added/updated to cover PowerShell and Rego changes.
- [X] All relevant functional tests passed.
- [X] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by tkol2022** [comment]
@crutchfield In the baseline document for AAD 5.3, the instructions, step 3 is wrong so we might as well fix it. Replace the existing step 3 description with "Under Security, select Consent and permissions. Then select User Consent Settings."

**Review by tkol2022 — APPROVED** [review]
### Test Results
I performed a live test for compliant and non compliant states specific to this setting in the G3, G5, GCC high and E5 tenants. The policy evaluation code worked as expected - no defects.

I also reviewed the functional test logic and it looks good. I examined the Rego and Powershell to ensure that the code changes align with the intent of the original issue which were to replace an unnecessary cmdlet.

**Comment by crutchfield** [comment]
> @crutchfield In the baseline document for AAD 5.3, the instructions, step 3 is wrong so we might as well fix it. Replace the existing step 3 description with "Under Security, select Consent and permissions. Then select User Consent Settings."

@tkol2022  Updated instructions for 5.3 step 3

**Review by ssatyapal123 — APPROVED** [review]
Ran successfully against E5. Unit and functional tests all passing.

**Comment by crutchfield** [comment]
@nanda-katikaneni PR ready to merge into main.

**Pull request merged**
