### PR TITLE
113 aad 24 title outdated

### PR DESCRIPTION
**Pull request by ssatyapal123**
#  #
Updated 2.4 Last Policy-Sub-bullet Title 
## 🗣 Description ##

Changed sub-bullet title to "MFA SHALL be required for all users"
## 💭 Motivation and context ##
The last sub-bullet needed to reflect the change in the Policy title.

## 🧪 Testing ##
Ran the unit test for aad,the Invoke-Scuba for aad and checked the report.

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Comment by adhilto** [comment]
@ssatyapal123, could you clarify what needed to be changed? Last sub-bullet, as in "SMS or Voice as the MFA method SHALL NOT be used"? If so, I don't see any changes made to that bullet. The only bullet I see a change for is "MFA SHALL be required for all users ", which now has a trailing space. Which makes me think I'm missing something.

Also, this branch has merge conflicts that need to be resolved.

**Comment by ssatyapal123** [comment]
@adhilto sorry for the confusion. In the report output, the last bullet was "Phishing-resistant MFA SHALL be required for all users", which is a repeat of the second bullet:
image
The change was to make the last sub-bullet "MFA SHALL be required for all users":
image

I couldn't get the code to work for that exact text. I noticed that any change to that specific text worked so I added a trailing space, thinking it would not harm the report output. Realize that I should have checked why that text wouldn't work but figured this issue should be a quick fix and went ahead. I would  be grateful if anyone knows where the conflict is.

**Comment by ssatyapal123** [comment]
@adhilto Sorry forgot to address your comment about merge conflicts. I think this is due to the reopening of the issue and the fact that I made the latest updates (to the sub-title vs the title) against the main branch but I'm looking into that now. Thank you, shanti

**Comment by adhilto** [comment]
What issue do you run into when you try to remove the trailing space? I tried it just now and it worked. Would be good to remove it, but either way you have my approval.

**Review by adhilto — APPROVED** [review]

**Comment by ssatyapal123** [comment]
@adhilto it was failing the unit Rego test for baseline policy 2.4 for some reason. But after checking it again just now, it is passing without any alterations to the text. So, I updated the code to remove the trailing whitespace. Thanks for your review, shanti

**Review by nanda-katikaneni — APPROVED** [review]
Looks good to me.

**Pull request merged**
