### PR TITLE
Boost AAD performance by replacing Cmdlets with slow load times

### LINKED ISSUE #816: prototype a performance redesign of the AAD provider
# 💡 Summary #

Perform hands-on prototyping with multi-threading and other techniques to determine if it is possible to significantly improve the performance of the AAD provider with a redesign of specific code blocks.

## Motivation and context ##

Currently the AAD provider is relatively slow because it has to fetch information about users and groups that are assigned to privileged roles and the current process invokes MS Graph API calls several times within multiple loops.

## Implementation notes ##

Develop and test various alternative implementation techniques for the Get-PrivilegedUser and Get-PrivilegedRole functions. Perform profiling to compare executions times of alternative implementations versus the current code. Keep profiling data in a spreadsheet for reference.

Some potential alternative implementation technique that may be considered are listed below. This is not an exhaustive list - the assignee can experiment with techniques not listed here.

- Using Powershell RunspacePool to perform concurrent Graph API requests
- Using [MS Graph JSON batching](https://learn.microsoft.com/en-us/graph/json-batching)
- Replacing the existing Powershell Cmdlets with direct calls to Graph API via Invoke-MgGraphRequest
- any ideas not covered here

## Acceptance criteria ##

- [ ] All techniques have been developed and tested with their profiling data collected

### PR DESCRIPTION
**Pull request by tkol2022**
#  #
  

## 🗣 Description ##

*This PR replaces #1094 which became too difficult to deal with since there were heavy merge conflicts - reference that PR for additional details.

The gist of this pull request was to modify the AAD provider so that we replace the Cmdlets in the Microsoft.Graph.Beta.Identity.Governance Powershell module with direct calls to MS Graph REST APIs. We found that the offending Powershell module takes a significant amount of time to load into memory when you call ScubaGear the first time in a fresh Powershell window. The good news was that the RESP API returns the same fields as the Cmdlet, except that the field names begin with a lower case letter so that is why you see those respective changes in the Rego and unit/functional tests as well as references in the AAD provider. 

closes #816

## 🧪 Testing ##

The original code changes were tested against the E5, G5, G3 and GCC High tenants. Additional testing should be done by the reviewers to ensure the code performs as expected and doesn't crash.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by tkol2022** [comment]
### For reviewers: How to test the performance improvement
The performance improvement when running AAD is mostly noticeable when the tool executes for the first time in a newly spawned Powershell window. This is because the slowness that we observed in the Microsoft.Graph.Beta.Identity.Governance dll was during its load into memory, which occurs only the first time you call one of its Cmdlets in a new Powershell window.
The steps below describe how you can test to ensure that you also see an improvement.

Use this code to take a time measurement (tailor the parameter values to your environment):
```
Import-Module -Name .\PowerShell\ScubaGear
$ExecutionTime = Measure-Command { Invoke-Scuba -ProductNames aad -CertificateThumbPrint "33dd41a761f434f12ee8ac3ff771347597435585" -AppID "ac691fde-1ff0-493f-be3d-03d9ba6cb891" -Organization "TEST_TENANT.onmicrosoft.com" }
$ExecutionTime
```

1. Download a copy of the main branch and run the measurement code above 5-10 times. Remember to take each measurement in a new Powershell window. Compute an average time.
2. Download a copy of the branch associated with this PR and repeat step 1.
3. Log the average time of the main branch and this branch in this PR.

**Comment by tkol2022** [comment]
@julianjburgos Test against the E5 tenant
@dagarwal-mitre Test against the G5 and G3 tenants

Follow the instructions in the prior comment above.

**Comment by dagarwal-mitre** [comment]
> @julianjburgos Test against the E5 tenant @dagarwal-mitre Test against the G5 and G3 tenants
> 
> Follow the instructions in the prior comment above.

Averages:
| Main  | New Branch |
| ------------- | ------------- |
G3: | 36.7 Seconds  | 38.3 Seconds  |
G5: | 98.1 Seconds  | 54.4 Seconds  |

**Review by dagarwal-mitre — APPROVED** [review]
See comment about average times, the time for the G3 tenant on average was slightly slower in testing

**Comment by tkol2022** [comment]
> See comment about average times, the time for the G3 tenant on average was slightly slower in testing

The Powershell code that was optimized affects tenants that are G5 and above.

**Comment by julianjburgos** [comment]
> @julianjburgos Test against the E5 tenant @dagarwal-mitre Test against the G5 and G3 tenants
> 
> Follow the instructions in the prior comment above.

Averages:
|  | Main  | New Branch |
| ------------- | ------------- | ------------- |
E5 | 127.1 Seconds  | 99.2 Seconds  |

**Review by julianjburgos — APPROVED** [review]
Look at comment above with average times for E5

**Comment by tkol2022** [comment]
@nanda-katikaneni ready for merge testing.

**Pull request merged**
