### PR TITLE
update supported opa versions to 0.61

### LINKED ISSUE #777: Add support for latest OPA v0.60.0
# 💡 Summary #

The latest version of the OPA Rego engine, v0.60.0, is now available but is not one of the supported versions for the ScubaGear tool.  Add support for 0.60.0 to the tool.

## Motivation and context ##

Supporting the latest version of Rego helps keep ScubaGear able to rapidly shift as needed when critical dependency changes are needed.  Additionally, v0.60.0 includes an OPA v1.0 compatibility mode that will help plan and test for eventual compatibility with the OPA v1.0 release in the futre.

## Implementation notes ##

Adding support would include:

- Adding the 0.60.0 version to the list of acceptable versions in the OPA.ps1 install script
- Testing the existing code using the 0.60.0 engine
- Updating the default install version to 0.60.0

## Acceptance criteria ##

How do we know when this work is done?

- [ ] The OPA.ps1 install script allows successfully installation of the 0.60.0 version of Rego
- [ ] Functional testing validates that the OPA 0.60.0 engine generates expected results for all tests
- [ ] The OPA.ps1 install script installs the 0.60.0 version of Rego by default.

### PR DESCRIPTION
**Pull request by Dylan-MITRE**
#  #
  

## 🗣 Description ##

ScubaGear supports up to 0.59.0. And the most recent OPA version is 0.61.0 now. Add latest support to the tool.

Adding the 0.60.0 and 0.61.0 version to the list of acceptable versions in the OPA.ps1 install script
Updating the default install version to 0.61.0

## 💭 Motivation and context ##

closes #777 

## 🧪 Testing ##

Run the OPA.ps1 or SetUp.ps1 to ensure it install the latest version of OPA (0.61.0)
Run .\Testing\RunUnitTests.ps1 to ensure all test still passes. 

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by Sloane4 — CHANGES_REQUESTED** [review]
You will need to update the default version in the SetUp.ps1 script as well

**Review by mitchelbaker-cisa — COMMENTED** [review]
README.md section will also need to be changed to v0.61.0 https://github.com/cisagov/ScubaGear/tree/777-add-support-for-latest-opa-v0600?tab=readme-ov-file#download-the-required-opa-executable

**Comment by Dylan-MITRE** [comment]
> README.md section will also need to be changed to v0.61.0 https://github.com/cisagov/ScubaGear/tree/777-add-support-for-latest-opa-v0600?tab=readme-ov-file#download-the-required-opa-executable

Good catch! thank you

**Comment by mitchelbaker-cisa** [comment]
> > README.md section will also need to be changed to v0.61.0 https://github.com/cisagov/ScubaGear/tree/777-add-support-for-latest-opa-v0600?tab=readme-ov-file#download-the-required-opa-executable
> 
> Good catch! thank you

Np! Going to pull this down locally to do a final check, will approve after.

**Comment by mitchelbaker-cisa** [comment]
Created reports for gcc/gcchigh licenses successfully, all unit tests pass. 

I did run a --strict Rego check and I'm getting these errors. @Sloane4 Any insight here? KeyFunctions.rego has `package utils.key` declared so wonder what it wants here. 
image

**Comment by Dylan-MITRE** [comment]
> Created reports for gcc/gcchigh licenses successfully, all unit tests pass.
> 
> I did run a --strict Rego check and I'm getting these errors. @Sloane4 Any insight here? KeyFunctions.rego has `package utils.key` declared so wonder what it wants here. image

seems like even with the older version 0.59 the check still complains about undefined function, so i suspect it might be something with the format of how the function is formatted (not entirely sure).   
Screenshot 2024-02-14 at 8 34 05 AM

**Comment by Sloane4** [comment]
@Dylan-MITRE @mitchelbaker-cisa 

It is because you are not sending the KeyFunctions.rego file through check. KeyFunctions.rego file is at `.\PowerShell\ScubaGear\Rego\Utils\KeyFunctions.rego`. In the command, you are only feeding the files under testing into opa check. Included examples below:
image

If I send all rego files under `.\PowerShell\ScubaGear` (1st case), no errors are produced). If I send all rego files under `.\PowerShell\ScubaGear\Testing` any functions defined in a file not in the testing directory or below it will be undefined (2nd case).

**Review by Sloane4 — APPROVED** [review]

**Review by mitchelbaker-cisa — APPROVED** [review]

**Comment by Dylan-MITRE** [comment]
@nanda-katikaneni should be ready to merge, smoke test fails due to an upstream bug in MSGraph SDK.

**Pull request merged**
