### PR TITLE
Added StackTrace multiple locations in source code to assist when troubleshooting

### LINKED ISSUE #1344: Implement standardized error message output including the stacktrace
# 💡 Summary #

Recently we analyzed how to modify ScubaGear to ensure that error message print statements are standardized and that they include the stacktrace. We also had problems that in some instances the stacktrace was wrong so that needs to be addressed too. Issue #1005 presents a solution with some sample code. The purpose of this issue is to formally incorporate those enhancements into ScubaGear.

## Implementation notes ##

- [x] Codify the enhancements discusses and prototyped in #1005 
- [x] The code must satisfy and be tested against the conditions noted below.

Conditions the code must satisfy:

- [x] Make sure error messages print the stack trace so that we can troubleshoot when problems occur.
- [x] Make sure the stack trace indicates the correct line where the error occurred. See example in comment below where the catch block inside the Invoke-ProviderList prints the wrong source lines.
- [x] Make sure the error handling logic correctly aborts execution under export provider failures. For example, right now the orchestrator continues to run additional logic if Export-AADProvider fails, which might not make sense.

### PR DESCRIPTION
**Pull request by tkol2022**
#  #
  

## 🗣 Description ##

Added the Powershell error stack trace to numerous locations in the source code to assist when troubleshooting bug reports.

I removed the try catch {} blocks in the following functions since the calling functions handle the stacktrace now: Get-PrivilegedUser, Get-PrivilegedRole, Invoke-Rego.

Closes #1344 

## 🧪 Developer Testing ##

I tested an error scenario or two for each of the functions that I modified to add the stacktrace and verified that the error information was displayed as expected. Results are documented in this PR.

## 🧪 Instructions for Reviewers ##

- Perform a code review to determine if any tweaks need to be made
- Conduct hands on tests by simulating error conditions and verify that ScubaGear prints the error message and stacktrace. You can use my test results as inspiration.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [x] Resolved all merge conflicts on branch
- [x] Notified merge coordinator that PR is ready for merge via comment mention
- [ ] Demonstrate changes to the team for questions and comments. 
    (Note: Only required for issues of size `Medium` or larger)

## ✅ Post-merge checklist ##

- [x] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by tkol2022** [comment]
### Tested scenario - ExportCapPolicies returns empty table
Expected result: make sure warning message displays, execution does not stop. No errors are thrown in this scenario.
Actual result: everything occured as expected

image

image

image

**Comment by tkol2022** [comment]
### Tested scenario - ExportCapPolicies returns invalid JSON
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. 
Actual result:

**Comment by tkol2022** [comment]
### Tested scenario - Error occurs inside Get-PrivilegedUser
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report indicates that the commands failed in the respective policies. 
Actual result: Everything happened as expected.

image

image

image

Second scenario - Error occurs inside a Get-PrivilegedUser nested function
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report indicates that the commands failed in the respective policies. 
Actual result: Everything happened as expected.

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Error occurs inside Get-PrivilegedRole
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report indicates that the commands failed in the respective policies. 
Actual result: Everything happened as expected.

image

image

image

Second scenario - occurs inside Get-PrivilegedRole nested function
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report indicates that the commands failed in the respective policies. 
Actual result: Everything happened as expected.

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Error occurs inside Get-TenantDetail
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. 
Actual result: Everything happened as expected.

image

image

image

image

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Defender Error occurs inside top level code - Invalid or missing Cmdlet
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report contains respective policy error.
Actual result: Everything happened as expected.

image

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Defender Error occurs connecting to ExchangeOnline
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop.
Actual result: Everything happened as expected.

image

image

**Comment by tkol2022** [comment]
### Tested scenario - EXO Error occurs inside top level code - Invalid or missing Cmdlet
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report contains respective policy error.
Actual result: Everything happened as expected.

image

image

image

**Comment by tkol2022** [comment]
### Tested scenario - EXO Error occurs inside Get-EXOTenantDetail
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report contains respective Tenant ID error.
Actual result: Everything happened as expected.

image

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Sharepoint Error occurs inside top level code - Invalid or missing Cmdlet
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report contains respective policy error.
Actual result: Everything happened as expected.

image

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Teams Error occurs inside top level code - Invalid or missing Cmdlet
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report contains respective policy error.
Actual result: Everything happened as expected.

image

image

image

Tested scenario - Teams Error occurs inside nested function Get-TeamsTenantDetail
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report contains respective error.
Actual result: Everything happened as expected.

image

image

image

**Comment by tkol2022** [comment]
### Tested scenario - PowerPlatform Error occurs inside top level code - Invalid or missing Cmdlet
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop. Report contains respective policy error.
Actual result: Everything happened as expected.

image

image

image
image

**Comment by tkol2022** [comment]
### Tested scenario - Connection > Disconnect-SCuBATenant
Expected result: make sure warning message displays with the error message, stacktrace.
Actual result: Everything happened as expected.

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Connection > Connect-Tenant
Expected result: make sure warning message displays with the error message, stacktrace.
Actual result: Everything happened as expected.

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Orchestrator > Invoke-ProviderList
Expected result: make sure warning message displays with the error message, stacktrace when executing one of the providers.
Actual result: Everything happened as expected.

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Orchestrator > Invoke-RunRego - All products failed
Expected result: make sure warning message displays with the error message, stacktrace and execution stops since all providers failed.
Actual result: Everything happened as expected.

image

image

### Tested scenario - Orchestrator > Invoke-RunRego - A single product failed
Expected result: make sure warning message displays with the error message, stacktrace and execution continues since only a single provider failed.
Actual result: Everything happened as expected.

image

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Orchestrator > ConvertTo-ResultsCsv - All products failed
Expected result: make sure warning message displays with the error message, stacktrace and execution does not stop since creating the CSV is not a critical task.
Actual result: Everything happened as expected.

image

image

image

**Comment by tkol2022** [comment]
### TODO - Future enhancements
The following items were observed as I was working this PR that I feel would be some good enhancements to the error handling logic in future issues.

#### Item 1 - Prevent duplicate error message displays from Merge-JsonOutput
When an error occurs in this function, it gets displayed twice in the console which really clouds up the output. It would be ideal to only display the same error message once. I believe this occurs because there is no catch {} block in the calling function Invoke-Scuba so what ends up happening is that the thrown error gets displayed a second time by Powershell itself.

image

**Comment by tkol2022** [comment]
### Tested scenario - Orchestrator > Invoke-ReportCreation - error occurred
Expected result: make sure custom message displays with the error message, stacktrace and execution stops since creating the report is a critical task.
Actual result: Everything happened as expected.

image

image

**Comment by tkol2022** [comment]
### Tested scenario - Orchestrator > Import-Resources - error occurred
Expected result: make sure custom message displays with the error message, stacktrace and execution stops since importing modules is a critical task.
Actual result: Everything happened as expected.

image

image

**Comment by tkol2022** [comment]
### Tested scenario - RunRego.psm1 > Invoke-Rego - error occurred
Expected result: I removed the try catch logic from this function since the calling function already has it so make the error message and stacktrace display and execution stops since invoking Rego is a critical task.
Actual result: Everything happened as expected.

image

image

**Review by nanda-katikaneni — COMMENTED** [review]
Did multiple tests with following simulated errors: incorrect M365 environment, errors in get priv user roles, errors in connecting exo, opa path error, convert to csv errors.
In each case, the stack trace showed expected error trace.

Apart from Addam's suggestion for updating warning format, no new suggested changes from me. Nice work.

**Comment by twneale** [comment]
Was able to connect with @schrolla and we decided to leave Compare-ProductList as is for now, because it's doing something different with throwing passed-in error messages.

**Comment by twneale** [comment]
@nanda-katikaneni This PR is ready to merge once you and @schrolla approve 👍

**Review by nanda-katikaneni — APPROVED** [review]
Retests went fine - approved.

**Pull request merged**
