### PR TITLE
Convert workflow testing code to functions

### PR DESCRIPTION
**Pull request by james-garriss**
## 🗣 Description ##

These two workflow functions were converted from modules to just functions.  There was no change in functionality.

## 💭 Motivation and context ##

Closes: #1429 

## 🧪 Testing ##

Tested via functional tests workflow and the workflow pipeline

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] These code changes follow the ScubaGear [content style guide]
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed
- [x] Resolved all merge conflicts on branch
- [x] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by james-garriss** [comment]
Summary of reasons for using functions in .ps1 files for workflow code:

1) They should not be part of the SG module, and there is no need for a testing module.
2) Functions support standard PowerShell options like -Debug.
3) Functions are easy to integrate into Pester tests.

Thus, the goal is move all workflow code into functions in .ps1 files and write unit tests for them that are executed by the workflow CI pipeline.

**Review by dagarwal-mitre — APPROVED** [review]
Looks good

**Comment by james-garriss** [comment]
@nanda-katikaneni

**Comment by mitchelbaker-cisa** [comment]
Ran functional tests, jobs pass excluding known SharePoint failures: https://github.com/cisagov/ScubaGear/actions/runs/11963450431
Ran workflow pipeline, pass: https://github.com/cisagov/ScubaGear/actions/runs/11963470997

**Pull request merged**
