### PR TITLE
Add app level defaults

### LINKED ISSUE #767: Config file default values are duplicated in Invoke-SCuBA parameters and ScubaConfig
# 💡 Summary #

The Invoke-SCuBA function parameter defaults and ScubaConfig parameter defaults should be shared and defined in one place

## Motivation and context ##

Invoke-SCuBA parameter defaults are specified in 2 places

1. The parameters section of the Invoke-SCuBA function
2. The SetParameterDefaults method of the SCuBA config object

This would be useful because maintenance of this code is complicated by the default values
residing in two places.

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

### PR DESCRIPTION
**Pull request by crutchfield**
#  #
  

## 🗣 Description ##

Added a ScubaDefault method to ScubaConfig class. 

## 💭 Motivation and context ##

closes #767 

The app had several entry points with potential for different default values (e.g., OPA Path).  This enhancement gives us a single location for Scuba default values that can be used through out the app.  

## 🧪 Testing ##

- Executed PowerShell unit test, all passed. 
- Executed Invoke-Scuba against a tenant, expected results. 

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [X] Changes are sized such that they do not touch excessive number of files.
- [X] *All* future TODOs are captured in issues, which are referenced in code comments.
- [X] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [X] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [X] All relevant type-of-change labels added.
- [X] All relevant project fields are set.
- [X] All relevant repo and/or project documentation updated to reflect these changes.
- [X] Unit tests added/updated to cover PowerShell and Rego changes.
- [X] Functional tests added/updated to cover PowerShell and Rego changes.
- [X] All relevant functional tests passed.
- [X] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Review by adhilto — APPROVED** [review]
Changes look good and work as expected.

**Comment by crutchfield** [comment]
@twneale You have time to review this PR?  If not let me know so I can re-assign.

**Review by twneale — APPROVED** [review]

**Comment by crutchfield** [comment]
@nanda-katikaneni Ready to merge into main

**Comment by crutchfield** [comment]
@nanda-katikaneni  Had to rebase (again) but ready to merge to main now

**Pull request merged**
