### PR TITLE
fixed AAD functional test failures for non-compliant tests 7.4 7.5 when running in GitHub actions

### LINKED ISSUE #1025: Entra ID or AAD Functional test failures for MS.AAD.7.4v1 and MS.AAD.7.5v1
# 🐛 Summary #

This issue was found through nightly product functional tests. Non-complaint test cases for MS.AAD.7.4v1 and MS.AAD.7.5v1 are failing on G5 and GCCHIGH tenants when run through GitHub action "Nightly functional product tests". However, the same tests are passing when run manually using a service principal. This issue and be used to debug and then fix the nightly product tests for aad.g5.testplan.yaml. 

We have two service principals in the test tenants: GitHubActions and FunctionalTesting. GitHub actions use the first service principal app, while the dev team use the second app service for internal on-demand testing. Manually ran tests using both these apps with my certificate thumbprint - tests ran fine on g5 and gcchigh. But tests from GitHub actions are consistently failing non-complaint test cases for 7.4 and 7.5 policies. These policy test cases are run using run cached mode and are structured differently from the complaint test cases. These two policy test cases should be investigated further to make the nightly product test automation have clean runs. 

## To reproduce ##

1. Run nightly product test GH action for the AAD G5 test plan.
2. Observe results and failures for 7.4 and 7.5 policies. 

## Expected behavior ##

The nightly product functional testing using AAD G5 test plan should have a clean run with all tests being executed and passed. 

Add any screenshots of the problem here.

### PR DESCRIPTION
**Pull request by tkol2022**
## 🗣 Description ##

AAD functional tests 7.4 & 7.5 were failing the non-compliant test cases when running in GitHub actions against the G5 and GCC high tenants. The root cause was the functional test cases hard coding the privileged_roles Assignments element [0] in the JSON array. That crashed in certain tenants so I modified the tests to create a JSON array that is deterministic and has a compliant and non-compliant Assignments element.

closes #1025 

## 🧪 Testing ##

I tested the GitHub actions Nightly Product Functional Tests to ensure that the G5 variant test plan worked against the G5 and GCC high tenants.

image

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by tkol2022** [comment]
> Not sure why but the non-compliant test cases were still passing for me even on main. Well they still pass for me on this branch also. 🤷
> 
> pass

They were only failing in the GitHub actions, which indicates that for some reason the JSON produced inside the GitHub container was somehow different enough to throw off the test. Hopefully these tweaks that I made will produce a more deterministic change to the JSON because I replaced the reference to the [0] element in the Assignments array - in general referring to a specific element index for the functional tests should probably be avoided where possible.

**Review by james-garriss — APPROVED** [review]
Ran the nightly tests using the 1025 branch and found that Ent_Tenant1 is still failing.  Is this PR supposed to fix that test as well?  If not, is there already an issue to fix it?  If not, please add one so that it is eventually addressed.  Otherwise, good work on fixing these.

image

A different question:  If I understand your detective work here, you have found that how we run manual tests and how the workflow runs them are different, so different that they were getting different results.  Is that a problem that should be fixed?  IOW, should we consolidate (if possible) how we run tests so that we eliminate these differences?  If yes, please open an issue for that.

**Comment by tkol2022** [comment]
> Ran the nightly tests using the 1025 branch and found that Ent_Tenant1 is still failing. Is this PR supposed to fix that test as well? If not, is there already an issue to fix it? If not, please add one so that it is eventually addressed. Otherwise, good work on fixing these.
> 
> image
> 
> A different question: If I understand your detective work here, you have found that how we run manual tests and how the workflow runs them are different, so different that they were getting different results. Is that a problem that should be fixed? IOW, should we consolidate (if possible) how we run tests so that we eliminate these differences? If yes, please open an issue for that.

**Question1**: Ent_tenant1 fix #1081 was merged to main last week and fixed policy 5.3 which was failing for that tenant.

**Question 2**: What I found is that the way the code was running in the container was likely producing a slightly different JSON compared to if I run the code with a service principal from my laptop. The JSON probably contains the same data, but I'm guessing in a different order and therefore this was throwing off the test case because the test case assumed that a specific data element was in position [0] in an array. So I adjusted the test case to create the JSON element without any dependencies on specific array positions.

**Comment by tkol2022** [comment]
@nanda-katikaneni  ready for merge

**Pull request merged**
