### PR TITLE
Update sharepoint.md with tech editor feedback

### LINKED ISSUE #510: Integrate technical editor feedback into SharePoint/OneDrive baseline
# 💡 Summary #

Review technical editor feedback on SharePoint/OneDrive baseline document and integrate suggestions into the baseline markdown.

## Motivation and context ##

Work belongs in emerald to ensure highest quality work and clear language prior to next release.

## Implementation notes ##

Technical editor feedback should be reviewed to:

- adjudicate comments and suggestions for action
- update baseline with spelling/grammar fixes
- incorporate comments with positive adjudication
- coordinate with technical editor for any comments/suggestions that are not implemented or are unclear

## Acceptance criteria ##

- [x] Technical editor comments and suggestions have been addressed and integrated into the baseline

### PR DESCRIPTION
**Pull request by ahuynhMITRE**
#  #

## 🗣 Description ##

This PR updates the SharePoint/OneDrive Secure Configuration Baseline to include grammatical, formatting, and other style and consistency related updates based on a review from the team technical editor.  Updates have been taken from a marked up version and added back into the markdown.

## 💭 Motivation and context ##

This change ensures the highest quality and clarity of the wording used in the baseline to make it easier to read for users.

Closes #510 

## 🧪 Testing ##

Test was to review the technical editor comments and suggestions and validate that the recommendations were consistent with the baseline technical language and improved the quality of the document.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Rebase branch against emerald prior to merge to incorporate latest changes.

## ✅ Post-merge checklist ##

- [ ] Validate no additional tests fail as a result of the merge.

### CODE REVIEW

**Comment by Dylan-MITRE** [comment]
everything looks good, should we also make changes to 1.3 to indiciate that we are currently only checking external domain but not checking the security groups half of the policy.

**Comment by tkol2022** [comment]
> everything looks good, should we also make changes to 1.3 to indiciate that we are currently only checking external domain but not checking the security groups half of the policy.

This should be noted in ScubaGear, not in the Markdown I don't think because we don't reference ScubaGear anywhere else in the baseline documents. Not sure exactly how we would display this in the report?

**Comment by Dylan-MITRE** [comment]
> > everything looks good, should we also make changes to 1.3 to indiciate that we are currently only checking external domain but not checking the security groups half of the policy.
> 
> This should be noted in ScubaGear, not in the Markdown I don't think because we don't reference ScubaGear anywhere else in the baseline documents. Not sure exactly how we would display this in the report?

ahh makes sense

**Review by Dylan-MITRE — APPROVED** [review]

**Review by tkol2022 — APPROVED** [review]
Approving with one minor tweak. Make this change for both "script" policies. The sentence is missing the word "the" before user.

"Scripts in OneDrive folders run in the context of the user visiting the site and have access to everything **the** user can access."

**Comment by ahuynhMITRE** [comment]
@nanda-katikaneni good to merge!

**Pull request merged**
