### PR TITLE
Add accessibility improvements to the reports 

### LINKED ISSUE #961: Unable to focus on dark mode switch when tabbing through HTML report
# 🐛 Summary #

When tabbing through the HTML report the user should expect anchors, links, and any input tags to be focusable. An element is considered focused when there is a black border around the tabbed element. 

The input is not focusable because its opacity = 0. 

## To reproduce ##

1. Run ScubaGear, go to either parent or individual HTML reports
2. Press the tab key. A black border will display around the CISA logo at the top left. Press the tab key again to navigate to the `Secure Cloud Business Applications (SCuBA)` link, again to the `Baseline Documents` link, then press it one more time.  
3. Technically pressing the space bar will toggle dark mode correctly. However, there's no visual indication to the user they've arrived at the switch. 

## Expected behavior ##

When tabbing through the HTML report a black border should appear around the dark mode switch, similarly to what's shown below.

Screenshot (30)

### LINKED ISSUE #972: Add aria labels that are missing in HTML report
# 💡 Summary #

There's a few instances where adding aria labels will help to improve accessibility of the HTML reports. 

## Motivation and context ##

Relates to #879 

WCAG 2.2

[Guideline 1.3.1 Info and Relationships](https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html)

[Guideline 4.1.2 Name, Role, Value](
https://www.w3.org/WAI/WCAG22/Understanding/name-role-value)

## Implementation notes ##

1. Light mode/dark mode is used to describe a checkbox input, add aria-labeledby attribute to better describe the relationship

```
<p id="toggle-text">Light Mode</p>
<label class="switch">
  <input id="toggle" type="checkbox" onclick="toggleDarkMode()" aria-labelledby="toggle-text">
  <span class="slider round"></span>
</label>
```

2. For "Expand all"/"Collapse all" buttons for the CAP table, a title attribute is used to display a tooltip. Add aria-label here to better describe the action for each button, e.g. "Expands all rows in the conditional access policy table"

```
<button title="Expand all" aria-label="Expands all rows in the conditional access policy table">+ Expand all</button>
```

## Acceptance criteria ##

How do we know when this work is done?

- [x] Elements in the HTML report should be given the attribute aria-label to provide an accessible name for situations when there is no visible label due to a chosen design approach
- [x] The aria-labelledby attribute should be used to associate a user interface control, such as a form field, with text on the page that labels it. 
- [ ] Smoke tests pass to indicate any added information displays correctly

### LINKED ISSUE #1047: Accessibility issues with CAP table
# 🐛 Summary #

There's a couple areas where the CAP table could be improved for accessibility purposes.

1. For each row there are chevron arrows with alt/title attributes both set to "Show more" or "Show less". Currently the alt/title attributes are read aloud with a screen reader as "Show more show more" which is redundant. It would help to include the CAP name here for additional info, ie "Show more for the Live - Session Length SHALL be Limited policy". This would also make use of a screen reader easier. 
2. The chevron arrows are image tags, so they can't be focused on with the tab key. [For WCAG compliance all functionality should be operable with a keyboard interface.](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html)  This also applies to "..." throughout the CAP table which when clicked expands the clicked row. 

## To reproduce ##

1. [Download NVDA](https://www.nvaccess.org/download/) for Windows or some other screen reader depending on your OS. Enable it. 
2. Generate a report for AAD 
3. Press tab to reach the CAP section of the report
4. Hover mouse over chevron icons to hear the repeated alt/title attributes

## Expected behavior ##

Users should be able to focus chevron arrows in the CAP table, and expand/collapse each row individually. This should also apply to "..." displayed throughout which also acts as a way to expand the given row. 

## Any helpful log output or screenshots ##

Screenshot (68)_LI

### LINKED ISSUE #1061: Accessibility improvements to HTML reports
# Description #

This epic focuses on making accessibility improvements to ScubaGear HTML reports. New issues were added to cover various use cases around navigating the tool with a screen reader when the reports were tested for 508/WCAG 2.2 compliance.

## Initiative / Goal ##

Address follow-up issues created from the previous epic, #820. 

## Acceptance criteria ##

How do we know when this work is done?

- [ ] New tests have been built or existing tests have been modified to validate HTML report changes work/look as intended
- [ ] Text content in HTML reports can be read by screen readers and functionality tied to inputs, links, and buttons are clear 
- [ ] Expand/collapse functionality in the CAP table can be reached with the tab key 

## Stakeholders / Resources ## 

Include CISA decision makers and dev team members in discussions about this epic. Resources needed for this epic include access to GitHub actions marketplace and ability to create new issue templates.

## Timeline ##
The current projected timeline for delivery of this epic feature is with the associated release milestone.

## Associated Tasks ##
See details in the following issues:

- [x] #961
- [x] #972 
- [x] #1047

### PR DESCRIPTION
**Pull request by mitchelbaker-cisa**
#  #
  

## 🗣 Description ##

Improves usability of the HTML reports with a screen reader as well as keyboard navigation support. 

## 💭 Motivation and context ##

This PR closes the epic #1061 which addressed follow-up issues found after testing for 508/WCAG compliance. 

Closes #1061 
Closes #961 
Closes #972 
Closes #1047 

## 🧪 Testing ##

- Used [NVDA](https://www.nvaccess.org/download/) to test screen reader accessibility across parent and individual reports.
- Tab through headers, dark mode switch, links, as well as CAP table which has expand/collapse arrows for each row.  
- Zoom in/out of the page to see if font size adjusts.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] Changes are sized such that they do not touch excessive number of files.
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [x] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels added.
- [x] All relevant project fields are set.
- [x] All relevant repo and/or project documentation updated to reflect these changes.
- [x] Unit tests added/updated to cover PowerShell and Rego changes.
- [x] Functional tests added/updated to cover PowerShell and Rego changes.
- [x] All relevant functional tests passed.
- [x] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [x] PR passed smoke test check.
- [x] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [x] Resolved all merge conflicts on branch
- [x] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by adhilto** [comment]
One thing I noticed is that the title text is also truncated with the dot dot dot (like so)
image

Is this the desired behavior? Definitely not essential but it might be nice to show the full policy name in the title as we don't have the same space constraints that we do visually.

**Comment by mitchelbaker-cisa** [comment]
> One thing I noticed is that the title text is also truncated with the dot dot dot (like so) image
> 
> Is this the desired behavior? Definitely not essential but it might be nice to show the full policy name in the title as we don't have the same space constraints that we do visually.

We're taking the .innerText to display in the title attribute, so if it's truncated then it'll show the "..." which isn't desired behavior. Will look into excluding the Name column from being truncated.

**Review by rgbrow1949 — APPROVED** [review]
Works as intended, approved

**Comment by mitchelbaker-cisa** [comment]
@nanda-katikaneni Ready to merge

**Pull request merged**
