### PR TITLE
Add AAD Error Handling

### LINKED ISSUE #83: ConvertTo-Json for "AAD"
modify all ConvertTo-Json in AAD provider script to $Output = ConvertTo-Json @(Get-ExampleCommand) for consistency and test to make sure the changes dont break the current code
related to #197

### PR DESCRIPTION
**Pull request by adhilto**
## 🗣 Description ##
- Updated all of the ConvertTo-Json calls to use the current syntax
- Wrapped all API calls inside the `TryCommand` function
- Updated Rego so that it always expects provider output items to be lists

## 💭 Motivation and context ##
Closes #83, #68, and #19.

## 🧪 Testing ##
- Ran code against Test Tenant 1 (G5) on both main and this branch, closely comparing output and ensuring that all differences are expected.
- Ran code against Test Tenant 2 (G3) on both main and this branch, closely comparing output and ensuring that all differences are expected.
- Ran code in Test Tenant 4 (E5) as an unprivileged user to generate errors. Ensured that all errors generated were handled correctly.
- Ran code in Test Tenant 4 (E5) as an admin after deleting all conditional access policies. Was able to reproduce the error described in #19 in main; bug is not present on new branch.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] ~~I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.~~
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Comment by tkol2022** [comment]
@nanda-katikaneni Please regression test this using the new semi-automated test script against Test Tenant 5 (E3) for AAD only.

- [ ] Generate golden copy of provider and test results using main branch code 
- [ ] Run semi-automated test script in the "add-error-handling" branch using Rego test option to make sure outputs are the same
- [ ] Run ScubaGear using the "add-error-handling" code and make sure the provider functions as expected

**Comment by rgbrow1949** [comment]
I compared the report results for my CISA account, my test account, and an account with no permissions on the main branch and on this branch. 

This account correctly displays Errors on the report in all cases, all unit tests pass, and the JSON outputs are correct as well without redundancies. 

I approve.

**Review by rgbrow1949 — APPROVED** [review]
I compared the report results for my CISA account, my test account, and an account with no permissions on the main branch and on this branch.

This account correctly displays Errors on the report in all cases, all unit tests pass, and the JSON outputs are correct as well without redundancies.

I approve.

**Comment by tkol2022** [comment]
> @tkol2022 I discovered a bug. You can see if by running `Disconnect-MgGraph` then the tool with `-Login $false` image
> 
> The issue is with how I handled $PrivilegedUsers. image Everything said in the comment is correct...but on error, `$TryCommand` returns an empty list, not a dict like the function normally does, resulting in invalid json.
> 
> I don't want to interrupt your testing. Should I fix this now or wait until you finish?

You can fix it now. Should not affect my testing. Thanks!

**Comment by tkol2022** [comment]
###  Not sure if this is a bug?
So I know you mentioned at today's meeting that there are some cases where a policy will be missing from the report if its respective provider Cmdlet fails but I can't remember the full context of what you said, so you may know about this already.

When the Get-MgDirectorySetting errors, the Baseline 2.7: Policy 3 "Group owners SHALL NOT be allowed to consent to third-party applications" gets excluded from the report.

image
image

**Comment by tkol2022** [comment]
### Might need to add logic to handle the scenario where Get-MgSubscribedSku fails
If Get-MgSubscribedSku fails, we should not call Get-PrivilegedUser and Get-PrivilegedRole because those functions depend on the list of SKUs to determine whether or not they should execute PIM-specific logic. Both of those functions have the line of code below:

  `  if ($TenantHasPremiumLicense) {`

You might need to add an if block to ensure that those functions are only called if Get-MgSubscribedSku succeeds. See my example below.

```
    $ServicePlans = $Tracker.TryCommand("Get-MgSubscribedSku").ServicePlans | Where-Object -Property ProvisioningStatus -eq -Value "Success" -ErrorAction Stop
    if($ServicePlans){
       ### Put all code that calls Get-PrivilegedUser and Get-PrivilegedUser HERE
    }

```

**Review by tkol2022 — CHANGES_REQUESTED** [review]
See comments. I will also test the error handling of Get-PrivilegedUser once you commit the fix you mentioned.

**Comment by adhilto** [comment]
> ### Not sure if this is a bug?
> So I know you mentioned at today's meeting that there are some cases where a policy will be missing from the report if its respective provider Cmdlet fails but I can't remember the full context of what you said, so you may know about this already.
> 
> When the Get-MgDirectorySetting errors, the Baseline 2.7: Policy 3 "Group owners SHALL NOT be allowed to consent to third-party applications" gets excluded from the report.
> 
> image image

Good catch. I thought this was worth fixing, so I just pushed a patch for it. We should fix all cases that we know cause something to be missing from the report. What I was saying in the meeting you referred to was that if there ever were something missing from the report (e.g., due to a Rego bug), we don't currently have code in place to flag that for the user, so unless catches it like you did, it will go unnoticed.

**Comment by adhilto** [comment]
> 

Added the logic you suggested.

@schrolla All requested changes have been made.

**Review by nanda-katikaneni — APPROVED** [review]
Tested main branch and the aad-error-handling branches on E3 tenant - results look fine. 
Note: that the aad-error-handling branch has an issue with automation code (the issue is since fixed in main through a separate merge) - so did tests with modified automation-script. The changes made in this branch looks good and does not conflict with automation changes - approving.

**Pull request merged**
