### PR TITLE
Add option to generate a config file template

### LINKED ISSUE #647: Add option to generate a config file template
# 💡 Summary #

What is the work, as a high-level summary?

Scuba need an option for the user to create a config file template 

## Motivation and context ##

Why does this work belong in this project?

The config file template will give the user a starting point (and understanding) for the config file options.  

This would be useful because the config file is necessary to take full advantage of Scuba capability.  

## Implementation notes ##

Please provide details for implementation, such as:

- Either -ConfigTemplate switch on Invoke-Scuba or use other separate cmd
- Template generator should accept Invoke Scuba parameters (e.g., ProductNames, M365Environment)
- Template should provide examples (e.g., reuse samples)
- Template should provide "help" for each config item

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Invoking generate template command produces a valid Scuba config file.

### PR DESCRIPTION
**Pull request by amart241**
#  #
  
Add option to generate a config file template

## 🗣 Description ##

A separate tool to make generate configuration files based on user input. 

## 💭 Motivation and context ##

This is an enhancement to make config files easier to make and understand. 
This tool makes the tedious task of generating a config file easier by allowing the user to change 
the template based on command line arguments. It will also just generate a default template if no arguments are passed.
This enhancement will resolve #647. 

## 🧪 Testing ##

To test this import the `Support` module and run `New-Config` passing any parameters that you want to change

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] PR targets the correct parent branch (e.g., main or release-name) for merge.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] Changes are sized such that they do not touch excessive number of files.
- [ ] *All* future TODOs are captured in issues, which are referenced in code comments.
- [ ] These code changes follow the ScubaGear [content style guide](https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
- [ ] Related issues these changes resolve are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels added.
- [ ] All relevant project fields are set.
- [ ] All relevant repo and/or project documentation updated to reflect these changes.
- [ ] Unit tests added/updated to cover PowerShell and Rego changes.
- [ ] Functional tests added/updated to cover PowerShell and Rego changes.
- [ ] All relevant functional tests passed.
- [ ] All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.

## ✅ Pre-merge checklist ##

- [ ] PR passed smoke test check.
- [ ] Feature branch has been rebased against changes from parent branch, as needed

  Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the command line.
- [ ] Resolved all merge conflicts on branch
- [ ] Notified merge coordinator that PR is ready for merge via comment mention

## ✅ Post-merge checklist ##

- [ ] Feature branch deleted after merge to clean up repository.
- [ ] Verified that all checks pass on parent branch (e.g., main or release-name) after merge.

### CODE REVIEW

**Comment by rgbrow1949** [comment]
The GenerateConfig.ps1 works just as intended. Before merging, fix the linter errors for trailing whitespace. Also, the branch is out of date and needs rebasing.
image

**Comment by crutchfield** [comment]
@amart241  This needs to be incorporated into the support module to support being delivered via PS Gallery.  We should not longer us stand alone scripts and use exported functions instead.

**Comment by rgbrow1949** [comment]
You have some trailing whitespace in a linter error, some pester errors and this branch needs rebasing
image

**Review by rgbrow1949 — APPROVED** [review]
Works as intended. The only linter error is on the linter's side: it doesn't recognize converto-yaml as a real module, which it is and it works to generate the config file. This needs a rebase but after it's ready.

**Comment by nanda-katikaneni** [comment]
@amart241 , please ping me after the linter issue is fixed and branch is rebased. thanks.

**Comment by amart241** [comment]
> @amart241 , please ping me after the linter issue is fixed and branch is rebased. thanks.

Ready for review

**Comment by amart241** [comment]
> @amart241 , please ping me after the linter issue is fixed and branch is rebased. thanks.

@nanda-katikaneni

**Review by nanda-katikaneni — APPROVED** [review]
Looks good - README is updated to explain the new sample-config file generation.

**Pull request merged**
