### PR TITLE
Update powerbi.md to align with tech editor comments

### PR DESCRIPTION
**Pull request by ahuynhMITRE**
#  #

## 🗣 Description ##

PowerBI baseline document has been updated based on tech editor feedback. The main changes are all grammatical and stylistic edits throughout the document. 

## 💭 Motivation and context ##

The tech-editor feedback is to make the baseline document consistent with other baselines and make any suggestions/edits for grammar and style. Most the feedback has been accepted with a few exceptions. The tech editor provided word document has more details. 

## 🧪 Testing ##

N/A

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Comment by ahuynhMITRE** [comment]
> @ahuynhMITRE rgbrow might be out for a few days. Suggest adding another reviewer.

gotcha, thanks for the heads up!

**Review by nanda-katikaneni — APPROVED** [review]
Looks good (changes are related to writing style/grammar). Approved.

**Comment by ahuynhMITRE** [comment]
> Looks good (changes are related to writing style/grammar). Approved.

thanks for the quick review nanda, good to merge!

**Comment by nanda-katikaneni** [comment]
The unit test failure is not related to PR - merging.

**Pull request merged**
