### PR TITLE
Added criticality to Power BI Markdown

### LINKED ISSUE #689: Explicility state criticality in Power BI product markdown
# 💡 Summary #
The criticality of a control/policy is generally embedded in the description.  An explicity statement of criticiality would allow for further automation.  

## Motivation and context ##

Better aligns Power BI markdown (i.e., secure baseline) with software baseline via automation for future proofing and consistency with other baselines.

## Implementation notes ##

Please provide details for implementation, such as:

- Update markdown with criticality for each policy
- Parse markdown to get criticality
- Use provided criticality instead of hard coded in rego files. 

## Acceptance criteria ##

How do we know when this work is done?

- [ ] All criticality is explicitly stated in markdown
- [ ] Rego uses provided criticality (No hardcoded criticality).

### PR DESCRIPTION
**Pull request by ahuynhMITRE**
## 🗣 Description ##

Added the html formatting for criticality to support new field in report for future proofing and consistency to match other baselines.

## 💭 Motivation and context ##

Criticality HTML is added to support new report field and supporting automation.  

Closes #689

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by crutchfield — APPROVED** [review]
Looks good.

**Comment by ahuynhMITRE** [comment]
> All 8 policy Criticality tags all conform to the format regex: `<--Policy: MS.POWERBI.\d\.\dv1; Criticality: SHOULD -->` So no misspellings or format variations, and exactly 8 matches found in the baseline. Verified that all policies have a matching criticality and policy ID relevant to the policy scope in which they are shown.
> 
> Looks good. Only question is does this go in v1.0.0 (main) or flipper? Currently, it's targeted at main so defaulting to v1.0.0.

fine with either since it will not affect the code at this time. Any reason not to put it in main / v1.0.0?

**Comment by ahuynhMITRE** [comment]
good to merge @nanda-katikaneni

**Comment by nanda-katikaneni** [comment]
@ahuynhMITRE - will merge this into flipper; please change the milestone for the associated issue #689 to flipper (its currently in emerald).

**Pull request merged**
