### PR TITLE
Add Regal for linting Rego

### LINKED ISSUE #559: Add in the OPA linter
# 💡 Summary #

What is the work, as a high-level summary?
The OPA team has recently released a version of a OPA linter that they are satisfied with. Now that is is stable & fairly roubust, should we include the linter in our CI/CD pipeline?

## Motivation and context ##

Why does this work belong in this project?
This linter allows for ignoring specific files & rules as well as only triggering warnings. Right now we have a style guide for the rego, but it is not enforced. With the linter we do not have to manually check for syntax errors, improving the readability of the code.

## Implementation notes ##

Please provide details for implementation, such as:

- https://github.com/StyraInc/regal

## Acceptance criteria ##

- [ ] Linter added into the pipeline
- [ ] Code updated for OPA style requierments

### PR DESCRIPTION
**Pull request by anderseknert**
#  #

## 🗣 Description ##

This PR adds [Regal](https://github.com/styraInc/regal) the Rego linter, to lint this project on PRs. Violations against Regal rules will be presented as annotations in PRs, and the full report printed to the logs.

I took the liberty of "fixing" two uncontroversial rules:

* [non-raw-regex-pattern](https://docs.styra.com/regal/rules/idiomatic/non-raw-regex-pattern)
* [use-assignment-operator](https://docs.styra.com/regal/rules/style/use-assignment-operator)

The rest of the violations reported have been configured to level `ignore` for now, and I've annotated the configuration file here with some explanations for most of them, should you want to look into having more of them enforced.

All of the rules are documented thoroughly in the [Regal docs](https://docs.styra.com/regal).

Finally, I've updated the OPA test job run in CI to include linting with Regal.

Fixes #559

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Comment by anderseknert** [comment]
If the failing smoke test is somehow related to this change, I could use some help in understand why 😊

Screenshot 2023-10-11 at 18 11 25

**Comment by crutchfield** [comment]
@anderseknert The smoke test issue is not related to the Rego Linter.  Issues appears to be we need to update how a selenium web driver for chrome is found.

**Comment by gdasher** [comment]
@anderseknert thanks so much for this.  would you mind retargeting it to the emarald branch?

Right now we're near releasing a big upgrade from that branch (including the baselines, so we temporarily stopped doing development on main) and it would be helpful if we target that branch as it will become main soon.

**Comment by anderseknert** [comment]
@gdasher doh! I had no idea 😅  Although it did seem odd that the last update to main was so long ago. I looked into rebasing but unsurprisingly, the number of conflicts to resolve there likely makes it easier to just build a new PR based off of that branch. I'll go for that.

**Comment by anderseknert** [comment]
Closing in favor of https://github.com/cisagov/ScubaGear/pull/594

**Pull request closed without merging**
